### ISSUE TITLE
P3 thank you

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#1014]
https://www.figma.com/file/hNqLtiygFfxJ7GdPmGgVyO/Sprint-2?node-id=567%3A503

<img width="222" alt="image" src="https://user-images.githubusercontent.com/8228248/71102140-ef74d600-2185-11ea-8b50-9c1e6efaf683.png">

**Comment by naomiseminega** [comment]
Page completed , styled and inserted in App. Awaiting to resolve commit error to push.
