### ISSUE TITLE
Turn on test code coverage check

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#1071]
## Summary

Add code coverage test. Note that this is build into our test framework, we essentially just have to add to `package.json`
```
    "coverage": "react-scripts test --coverage --watchAll=false",
```
and then add this to our CI testing and configure it appropriately.

## Motivation

It's a good process to do and also a specific ask from RCMP.

## Drawbacks

We will have to reconfigure coverage testing as needed (for example, if we add a file that we do not want to be included).

## Unresolved questions

What should our coverage thresholds be?

**Comment by khalidelaggan** [comment]
I have already added this while I'm playing with Testing so will create a sweat PR for this shortly :)

**Comment by sastels** [comment]
partially done in #1146 - just need to decide on sensible thresholds and then add it to our CI pipeline

**Comment by justinr86** [comment]
What is the status of this issue? In Master package.json contains the following:

"coverage": "SELF_HARM_WORDS= react-scripts test --coverage --watchAll=false"

Does this satisfy requirements?
