### ISSUE TITLE
Change Privacy and Terms and Conditions to RCMP--wait until "privacy" and " Terms and conditions" page created

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#1094]
## Summary

When it launches, the app footer will need to link to the RCMP Privacy Statement and the T&C that RCMP has.

## Design Detail

![Screen Shot 2020-01-14 at 3 59 47 PM](https://user-images.githubusercontent.com/38330843/72382272-e7f20f80-36e6-11ea-9b43-33e264cdcf8b.png)

**Comment by DianeLiu2019** [comment]
wait until "privacy" and " Terms and conditions" page created
