### ISSUE TITLE
Add validation on 'What could be affected?' page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#1096]
## Summary

Add validation to the 'What might be affected?' page

## Design Detail
Prompt in case no box is checked.
![Screen Shot 2020-01-14 at 4 05 58 PM](https://user-images.githubusercontent.com/38330843/72382670-c5acc180-36e7-11ea-8897-0da03441a57e.png)

## Drawbacks
Could cause some friction if no option applies?

**Comment by khalidelaggan** [comment]
I will be happy to work on this :) Is this scoped for this sprint?

**Comment by naomiseminega** [comment]
Solved by PR#1214
