### ISSUE TITLE
Confirmation page doesn't load on Firefox  and Safari

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#1112]
## Summary

Confirmation page doesn't load on Firefox or Safari anymore. Just get blank screen. Possibly related to the `intl` library we introduced this week.

Chrome is fine.

## Steps to reproduce

Open Firefox and go to confirmation page. through app or directly both have issues.

## Unresolved questions

none

**Comment by amazingphilippe** [comment]
Might be requiring a polyfill, even just for the format list. We should also check on IE

https://www.npmjs.com/package/@formatjs/intl-listformat

**Comment by amazingphilippe** [comment]
More documentation: 

https://github.com/formatjs/formatjs/tree/master/packages/intl-listformat/src
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ListFormat

**Comment by khalidelaggan** [comment]
My work progress on this issue will be listed here :
Step #1:  reproducing the issue now

**Comment by khalidelaggan** [comment]
Including a screenshot of the generated error to make it clear 

<img width="1065" alt="Screen Shot 2020-01-24 at 10 50 29 AM" src="https://user-images.githubusercontent.com/2603117/73082395-65f8a800-3e97-11ea-95f2-f50be1c1d2f1.png">

**Comment by sastels** [comment]
Possibly the easiest thing to do for now (ie if getting a polyfill to work is difficult) is to just reimplement the conjunction logic (for English and French) ourselves.

**Comment by khalidelaggan** [comment]
@sastels agreed!! to add a polyfill is a cumbersome task, and it isn't really necessary where we can fix it with a simple script 
https://github.com/cds-snc/report-a-cybercrime/pull/1215/files

**Comment by khalidelaggan** [comment]
I believe this is working now, thank you @amazingphilippe! I may add in a feature enhancement task to implode the array with “, ” and add “and ” in a better constructive re-usable form.

I just don't want to hold any testing/fixes due to this issue and need to get this out of the door first.

**Comment by sastels** [comment]
closed by #1215
