### ISSUE TITLE
Page focus is not consistently at the top of pages

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#1142]
## Summary

As you click through the form, the focus loads the page at different points rather than consistently at the top. This is especially noticeable on longer pages such as the money, information, device and business pages as well as on the suspect tinfo page.

**Comment by khalidelaggan** [comment]
Can I work on this one? I find this a great opportunity to discover the page rendering/painting engine react.

**Comment by khalidelaggan** [comment]
A quick question no need to rush in for an answer :) 

Do you always want it to scroll? As for instance if someone presses the back button you may want to take them to the location that they were on when they went back.

**Comment by anikbrazeau** [comment]
I think we want it to load with the top of the page so people see the title and can choose to scroll down.

**Comment by sastels** [comment]
https://github.com/ReactTraining/react-router/issues/5210
