### ISSUE TITLE
Add progress indicator or stepper feature

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#1144]
## Summary

Eventually, add progress indicator or stepper feature to show users where they are at in the form with (step X of Y)

## Design Detail

<img width="207" alt="Screen Shot 2020-01-16 at 12 33 36 AM" src="https://user-images.githubusercontent.com/38330843/72496572-00058400-37f8-11ea-9f9c-8f0e9b092a71.png">

It appears this was on the confirmation page while under construction. 

## Drawbacks

Tradeoff if it's too long it could discourage continuation.

**Comment by khalidelaggan** [comment]
@sastels  I can help with this one if it's not under someone else's radar.

**Comment by khalidelaggan** [comment]
Here is a great tips on creating a progress tracker that may suit our needs 

https://medium.com/swlh/creating-a-progress-bar-in-react-181501bc22f1

**Comment by amazingphilippe** [comment]
I'm closing this issue for now. After doing some research on paper, as well as with participants, we found out a progress indicator is likely to not do any difference in usability. See this [figma board](https://www.figma.com/file/R054FzUOrpP13oTbMsQevj/Sprint-4?node-id=1014%3A20481) to follow the evolution of this issue.

Key reasons to close this issue:

- Lack of evidence proving a stepper really improves usability
- Complexity to implement a stepper or progress bar on conditional forms
