### ISSUE TITLE
Entries not showing up on confirmation page when filled out

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#1148]
## Summary

Missing entries include
- How did the crime start? 
- Money or finances

## Steps to reproduce

Fill out form with these sections to see if they appear on confirmation page.

After filling out every field, got this:

<img width="404" alt="Screen Shot 2020-01-16 at 7 53 22 AM" src="https://user-images.githubusercontent.com/38330843/72526843-504f0700-3835-11ea-81f0-c44bb9129739.png">

**Comment by amazingphilippe** [comment]
I don't see the money block, but I see the start block. Although there are other problems. I've created a new issue for these :

**Comment by sastels** [comment]
Money blocked fixed in #1156

**Comment by amazingphilippe** [comment]
I think this is now all fixed based on our previous comments
