### ISSUE TITLE
Checkboxes don't all link up to the pages if multiple are selected

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#1149]
## Summary

When all checkboxes are selected, you are not taken through all subsequent page:
- Money or finances
- Personal information
- Devices or accounts
- Business assets

## Steps to reproduce

Select all 'what could be affected' checkboxes and continue through flow

<img width="426" alt="Screen Shot 2020-01-16 at 7 57 16 AM" src="https://user-images.githubusercontent.com/38330843/72527039-d5d2b700-3835-11ea-9f32-813cfcd2d318.png">

**Comment by amazingphilippe** [comment]
I'm going through all of them on chrome. I've noticed that clicking the cancel report button prevents you from going through these pages, just like you are experiencing. (#1106) 

A temporary workaround for this is to click the cancel report button AND refresh the page.

**Comment by sastels** [comment]
So I think this is working? @anikbrazeau @amazingphilippe are we good to close this?

**Comment by DianeLiu2019** [comment]
I tested if one checkbox selected, it will go to the related pages. If all the checkbox selected, it will go to all the page. waiting Anik to confirm if we need to work on the issue

**Comment by sastels** [comment]
confirmed over Slack 🎉
