### ISSUE TITLE
Empty divs on confirmation page

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/report-a-cybercrime#1153]
## Summary

- How did it start block could get better labels
- Empty blocks are being rendered on the page and creating empty space

## Steps to reproduce

1. Fill out first starting _channel_ option: "by email", choose any _when_ and _frequency_ option
2. Skip to confirmation
3. See empty space between _channel_ and _when_ created by empty divs. 
4. Also see identical description titles for _when_ and _frequency_

<img width="839" alt="Screen Shot 2020-01-16 at 9 15 08 AM" src="https://user-images.githubusercontent.com/5230720/72532399-58ad3f00-3841-11ea-862a-5357807ee82e.png">

**Comment by sastels** [comment]
yeah i noticed that spacing issue. Probably the best solution is to remove the `spacing` prop from the `<Stack>` blocks, then put space at the bottom of the `<DescriptionListItem>` blocks if they're not empty.

**Comment by khalidelaggan** [comment]
Working on this now 👍

**Comment by sastels** [comment]
Gonna remove the high priority for now - we can fix it next week.

**Comment by amazingphilippe** [comment]
I was just looking through this, and we only have to remove `shouldWrapChildren`. Since `<DescriptionListItem>` generates a block element, it does not need to be wrapped again to form the Stack!
