### ISSUE TITLE
Conditional fields stay in local state after unchecking their conditional checkbox-- for Sprint 4

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/report-a-cybercrime#1171]
## Summary

Unchecking a conditional checkbox does not remove its associated data in other fields on the What was affected page

## Steps to reproduce

1. Enter data in one conditional field
2. Jump to summary
3. Edit from summary
4. Uncheck your selected checkbox
5. Return to summary
6. Data is still there. 

## Unresolved questions

We probably have the same problem with ~~What was affected~~ How did it start page

**Comment by amazingphilippe** [comment]
Updated the issue. Had mixed up How did it start and What was affected pages

**Comment by DianeLiu2019** [comment]
This task was completed ,associated with PR#1250
