### ISSUE TITLE
[Page footer]Ensures that lists are structured correctly

### ISSUE THREAD

**Issue by khalidelaggan** [cds-snc/report-a-cybercrime#1175]
## Summary 

`<ul> and <ol> must only directly contain <li>
`

 **Currently it contains an anchor tag instead** 

<img width="460" alt="Screen Shot 2020-01-19 at 6 14 35 PM" src="https://user-images.githubusercontent.com/2603117/72690194-fcb81400-3ae7-11ea-9b7a-304e37cafcac.png">
<img width="375" alt="Screen Shot 2020-01-19 at 6 14 40 PM" src="https://user-images.githubusercontent.com/2603117/72690195-ffb30480-3ae7-11ea-8066-5e3f1a04c710.png">

## How to Fix

Please enclose all anchor tags within `<li>` tags

<img width="518" alt="Screen Shot 2020-01-19 at 6 15 15 PM" src="https://user-images.githubusercontent.com/2603117/72690197-03468b80-3ae8-11ea-99b4-f19521ce8d9f.png">

**Comment by amazingphilippe** [comment]
Fixed in #1233
