### ISSUE TITLE
[location] Incorrect form inputs IDs/names

### ISSUE THREAD

**Issue by khalidelaggan** [cds-snc/report-a-cybercrime#1178]
## Summary

> Voice Over prompts the user with the wrong information to fill in due to incorrect/mismatched IDS

<img width="387" alt="Screen Shot 2020-01-19 at 7 43 35 PM" src="https://user-images.githubusercontent.com/2603117/72691543-34c55400-3af4-11ea-87ec-01e93c10fa94.png">

<img width="429" alt="Screen Shot 2020-01-19 at 7 45 35 PM" src="https://user-images.githubusercontent.com/2603117/72691558-50305f00-3af4-11ea-881c-ddb2012f4a50.png">

<img width="382" alt="Screen Shot 2020-01-19 at 7 43 18 PM" src="https://user-images.githubusercontent.com/2603117/72691544-34c55400-3af4-11ea-96a8-bcf93cb87dbb.png">

<img width="470" alt="Screen Shot 2020-01-19 at 7 45 38 PM" src="https://user-images.githubusercontent.com/2603117/72691556-4f97c880-3af4-11ea-91dd-9b789cca805d.png">

## Recommended Solution 
<img width="520" alt="Screen Shot 2020-01-19 at 7 51 44 PM" src="https://user-images.githubusercontent.com/2603117/72691673-35121f00-3af5-11ea-8292-4d811a983c5b.png">

**Comment by amazingphilippe** [comment]
@khalidelaggan I would suggest creating a component, or a test, to prevent this type of issue from happening again. This is the result of too much copy-pasting, and less writing. A component approach also implies we would make a test, and might also be easier to write.

**Comment by amazingphilippe** [comment]
This branch is a WIP exploring this particular idea. Feel free to drop in. https://github.com/cds-snc/report-a-cybercrime/tree/FieldComponent
