### ISSUE TITLE
use Azure Keyvault

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#1189]
## Summary

We need to store our app secrets in Keyvault rather than just putting them in App Service

## Motivation

Best practices, as well as an RCMP requirement.

## Drawbacks

Code around secrets becomes more complicated, and there are more pieces to maintain.

## Unresolved questions

None.

**Comment by sastels** [comment]
@ngosset Do we need this for launch?

**Comment by ngosset** [comment]
We said we were going to use keyvault in the SA&A, so I would say yes. If
we use an alternative, we need to update the SA&A.

**Comment by sastels** [comment]
@davidheerema are the prod apps configured to use keyvault?

**Comment by davidheerema** [comment]
@sastels No, I suggest we hold off on your keyvault PR until after the release at this point in time - I don't want to introduce anything new.  Is that fair?

**Comment by sastels** [comment]
> @sastels No, I suggest we hold off on your keyvault PR until after the release at this point in time - I don't want to introduce anything new. Is that fair?

@ngosset Is this OK?

**Comment by davidheerema** [comment]
Yes, the values are still encrypted in the app secret.  Either way, I don't
yet have time getting this to work today anyways - I am working on other
things and integrating a keyvault into the subscription might take me too
much time.  Once I get this thing running fine then we can revisit - who
knows, that may be before launch - im working evenings too.

**Comment by davidheerema** [comment]
Removing need for launch from this.

**Comment by ngosset** [comment]
I think this can be closed, will discuss with @davidheerema

**Comment by davidheerema** [comment]
Close it.  Delete the branch?  We have so many stale branches kicking
around.
