### ISSUE TITLE
Restore heading level 1 on all pages

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/report-a-cybercrime#1199]
## Summary

Since we decided to remove the stepper, we must revert some changes made to all page's H1

## Details

<img width="499" alt="Screen Shot 2020-01-23 at 9 59 06 AM" src="https://user-images.githubusercontent.com/5230720/72995479-016e1800-3dc7-11ea-9774-9a28a86f4a1e.png">

## Drawbacks

Lots of file changes

## Unresolved questions

In the future, IF an empirical decision is made to add a stepper, we might have to address how the headings reflect progress for voice-over users. It also might have no incidence on the H1.

**Comment by kevinyang06** [comment]
any idea how many pages should be change?
