### ISSUE TITLE
Update the server.js to save files to CosmosDB.

### ISSUE THREAD

**Issue by ngosset** [cds-snc/report-a-cybercrime#1217]
## Summary

Issue #1216 is a pre-requisite to this. We need to save a file upload to CosmosDB. Update the current server.js to save files as attachments to reports.

CosmosDB Attachments documentation here: https://docs.microsoft.com/en-us/rest/api/cosmos-db/attachments

## Motivation

Files aren't being saved at all.

## Drawbacks

With great power comes great responsibility... Now we're responsible for files!

## Unresolved questions

Probably need issue #1216 complete first
-Need Anti virus scanning
-Need Content Moderator scanning

**Comment by sastels** [comment]
@ngosset you had some thoughts about saving to Blob Storage vs CosmosDB?

**Comment by ngosset** [comment]
> @ngosset you had some thoughts about saving to Blob Storage vs CosmosDB?

I didn't have a ton of time to look at it yet, so take this all with a grain of salt.

Microsoft publishes a nodejs library for Azure which can make this really easy for Blob Storage. For CosmosDB I'm not sure if it'd be just as easy or if we have to craft a POST by hand. Also couldn't find a ton of example code for saving files to CosmosDB, while there's plenty for blob storage.

**Comment by ngosset** [comment]
https://www.npmjs.com/package/azure-storage

**Comment by ngosset** [comment]
And similar for CosmosDB:
https://stackoverflow.com/questions/45844444/how-do-i-get-an-attached-file-from-cosmosdb-using-nodejs-sdk

So either way we can use the sdk and avoiding crafting our own POST. 

I've found some old stackoverflow comments saying CosmosDB has a file attachment limit of 2GB total per Azure account though, but can't find that in the docs anymore.  And comments that CosmosDB attachments are more expensive than blob. Blobs probably best?
