### ISSUE TITLE
Bug - French translation on "suspect clues" page is partly in English

### ISSUE THREAD

**Issue by melbanyard** [cds-snc/report-a-cybercrime#1242]
> Participant noted that part of this phrase was in English. I am not 100% which lines they were but if we could check how consistently question 2 and 3 were translated, that'd be superb.

**Comment by kevinyang06** [comment]
I went through all French translation and I did't see any English text

**Comment by anikbrazeau** [comment]
French looks good now:

<img width="874" alt="Screen Shot 2020-02-05 at 10 08 57 AM" src="https://user-images.githubusercontent.com/38330843/73853877-90375780-47ff-11ea-80a7-60f08506cdab.png">
