### ISSUE TITLE
The incident report is not reset when the user clicks on Cancel or Create a new report

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1249]
## Summary

The incident report is not reset when the user clicks on Cancel or Create a new report

## Steps to reproduce

1. Open the NCFRS webpage
2. Click on Report Now
3. Click on checkbox and continue
4. Choose "By email" and "By phone",  "Today", "Once" and press "Continue" button
5. Choose "Personal Information" on the next screen and then press "Cancel" or "Cancel" button on the next page

Expected Result: The report should be reset
Actual Result: The report is not reset. The info that the user entered is still displayed

It also happened when the user presses the "Create a new report" option on the thank you page

## Unresolved questions

N/A

**Comment by amazingphilippe** [comment]
There needs to be an intermediate cancellation page. This issue will have to work with this new page.
