### ISSUE TITLE
When running project from source on a Windows machine, lingui doesn't work

### ISSUE THREAD

**Issue by ngosset** [cds-snc/report-a-cybercrime#1252]
## Summary

Lingui isn't working when the app is run locally on Windows Machines 

## Steps to reproduce

If you download the project on a Windows machine and do a 'npm run dev' you are given a borked version of the app without the lingui labels. This also happens if you do a full build and run 'node server.js'

## Unresolved questions
\

**Comment by ngosset** [comment]
![screen1](https://user-images.githubusercontent.com/2212291/73570198-e55b1e00-4439-11ea-9c26-443bb12c9317.png)
![screen2](https://user-images.githubusercontent.com/2212291/73570199-e55b1e00-4439-11ea-8a42-87e3f201a881.png)

**Comment by ngosset** [comment]
**WORKAROUND** Works fine within "Windows Subsystem for Linux"

**Comment by sastels** [comment]
@ngosset So are we good to close this and just assume that dev work will be done under linux?

**Comment by ngosset** [comment]
Unsure. Dev work can be done fine in Win10 by using Windows Subsystem for
Linux, which is also ideal as it more closely reflects the environment in
our container than running natively in Windows.

However it'd be a nice to have. Also Hong is stuck on Win7 until she gets a
new laptop.

**Comment by lmcbhvu** [comment]
@ngosset Norm: I run on Win10 of your laptop and I still get the same error. Khalid will help me to take a look  at this on next week

**Comment by ngosset** [comment]
@lmcbhvu

Yes you would need to run it in "Windows Subsystem for Linux" which is an
add-on you need to install in Windows 10, and then you need to install a
Linux distro from the Microsoft app store and install the app inside in the
subsystem/distro. I can also show you sometime

**Comment by lmcbhvu** [comment]
To resolve the problem with lingui on window machine, here is John's solution 
1. Go to the i18n.config.js, change line 14 to `./locales/${locale}.js`
2. npm run build
3. npm run compile.

**Comment by ngosset** [comment]
@lmcbhvu @sdzhangtao  It might make sense to add a PR for John's fix into github if it doesn't break it in Unix or Mac and then we can close this issue. Thoughts?

**Comment by lmcbhvu** [comment]
I agree but someone with Mac need to verify it.

**Comment by ngosset** [comment]
Believe this is fixed or appropriately worked-around now. Large part of team working on Windows now.
