### ISSUE TITLE
Restrict file upload by file extension and size.

### ISSUE THREAD

**Issue by ngosset** [cds-snc/report-a-cybercrime#1256]
## Summary

We are using FRS as a baseline for file upload.
We should have the same upload restrictions: jpg, jpeg, doc, docx, xls xlsx, pdf, txt, rtf. File size restriction: 4MB

## Motivation

Limiting the amount of stuff we can receive at the start. We can iterate on this and adjust as needed.

## Unresolved questions
FRS also limits a user to 3 uploads per complaint, but is this necessary? 
How many 4MB files can we fit in an e-mail through RCMP mail gateway?
OCRE allows pngs, I don't think it would hurt to add pngs to start?

**Comment by sastels** [comment]
@naomiseminega what's the status of this issue?

**Comment by sastels** [comment]
Client side is done. Should check server side.

**Comment by naomiseminega** [comment]
@sastels Server side is done as well, but I had trouble showing a response on the server (it keeps saying uncaught promise). I'll need your help please :)
