### ISSUE TITLE
IE - Cannot go back to home page or your privacy page

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1279]
## Summary

The homepage or your privacy page should be displayed instead of bank page if the user clicks on the "Privacy" or "Terms and Conditions" on the homepage or your privacy page and use an back arrow to come back to previous page
It happened on Internet Explorer, not on Google Chrome or Firefox

## Steps to reproduce

1. Open the incident report page on Internet explorer
2. Click on Privacy or Terms and Conditions
3. Use back arrow to come back to previous page
Expected Result: The previous page will be displayed (incident report page)
Actual page: An emplty page is displayed

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
This should be fixed when we make our own versions of these pages

**Comment by amazingphilippe** [comment]
I'm having trouble reproducing the bug consistently. Tried with IE10 on Windows 8 and IE11 on Windows 7. 

We'll still have external pages, we should investigate this more.

console refers to this page when navigating externally: https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/dev-guides/dn265017(v%3dvs.85)

**Comment by sastels** [comment]
Privacy and Terms and Conditions pages now open in their own tab without a back button.
