### ISSUE TITLE
Stop using @reach/component-component

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#1282]
## Summary

We're using `@reach/component-component` in `TrackPageViews.js`. We should stop doing this (we don't even use the reach router anymore) and use react hooks instead.

## Motivation

Get rid of a dependency

**Comment by gooseNjuice** [comment]
Can I try to solve it?

**Comment by sastels** [comment]
> Can I try to solve it?

Be my guest! 😄
