### ISSUE TITLE
The beginning of page is not displayed when it moves to the next page

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1296]
## Summary

When the user completes to fill out the current page and move the next page, the end of page is always displayed instead of the beginning of the page

## Steps to reproduce

1. Launch the application
2. Click on Report now button
3. Click on continue button of privacy page
4. Fill out the info on the incident page and press <Continue>
Expected Result: The beginning of next page will be displayed
Actual Result: The end of next page is displayed

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by amazingphilippe** [comment]
Same issue as #1142
