### ISSUE TITLE
The message from the thank you page should be changed

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1299]
## Summary

On the thank you, the message "We've sent you an email with a summary of your report . Your reference number is  ....." should be changed because we give the user the choice to enter email address or phone on contact detail page. It does not make sense if the user enters the phone number only

## Steps to reproduce

N/A

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
fixed in a PR
