### ISSUE TITLE
Add an input field for "Other" on the "What was affected" page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#1309]
## Summary

Other should have an additional input field on the "What was affected" page

## Design detail

https://www.figma.com/file/R054FzUOrpP13oTbMsQevj/Sprint-5?node-id=1984%3A0

<img width="204" alt="Screen Shot 2020-02-06 at 4 16 14 PM" src="https://user-images.githubusercontent.com/38330843/73979386-0a4d0680-48fc-11ea-8b49-8bb32aef1724.png">
<img width="201" alt="Screen Shot 2020-02-06 at 4 16 20 PM" src="https://user-images.githubusercontent.com/38330843/73979389-0b7e3380-48fc-11ea-88cf-38fab302db72.png">

**Comment by naomiseminega** [comment]
@anikbrazeau , I believe this was solved by a merge I did yesterday. Check again ;-)

**Comment by sastels** [comment]
@anikbrazeau @naomiseminega are we good to close this? 😄
