### ISSUE TITLE
Subheading on what happened page is too large, make sure it matches other pages format

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#1311]
## Summary

Make sure the text on the "What happened" page matches the style of text on other pages.

## Design Detail

<img width="952" alt="Screen Shot 2020-02-06 at 4 31 55 PM" src="https://user-images.githubusercontent.com/38330843/73980449-35d0f080-48fe-11ea-8ac0-3afca32683cc.png">

**Comment by amazingphilippe** [comment]
This seems to be okay
