### ISSUE TITLE
The info is not updated correctly after edit at review page

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1313]
## Summary

At the review page, the user wants to update the way of communication in the how the incident start page by removing one of entry, the review page is update but the detail info is still there.
Please see the attached file for more info
![incident](https://user-images.githubusercontent.com/60269104/73999491-e6f17e00-4932-11ea-8621-dc303005fda3.jpg)

## Steps to reproduce
1. At how the incident start page, choose email (enter email address in the box) and phone (enter phone number in the box)
2. Fill out the remaining required info and move to the review report page
3. Click on Edit button of How did the incident start? section
4. Uncheck the email box but not removing the email address in the box

Expected Result: The suspect 's email should not be displayed
Actual Result: The first sentence is updated (I was contacted by phone) but the suspect's email is still displayed

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by lmcbhvu** [comment]
It is applied to all of options in How did the suspect reach you? section

**Comment by lmcbhvu** [comment]
I closed it by accident.

**Comment by sastels** [comment]
we can check when the user gets to confirmation page and clear those fields then
