### ISSUE TITLE
Resubmit same report by going back

### ISSUE THREAD

**Issue by davidheerema** [cds-snc/report-a-cybercrime#1316]
Hey Everyone,
Maybe this has been raised already but on one of my experiments using the product I noticed that after I received my confirmation number on the confirmation page I can hit back in the browser and either re-submit or forward again and it will re-submit the report again.

Maybe after we submit we want to clear the data?

**Comment by sastels** [comment]
we can probably just clear the data when the user gets to the thank you page as Dave suggests
