### ISSUE TITLE
No comma between the options in What could be affected? of review report page

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1318]
## Summary

No comma between the options in What could be affected? of review report page
Please see the file
![review1](https://user-images.githubusercontent.com/60269104/74050593-64090b80-49a4-11ea-9f74-34ca3d2cdb6e.jpg)

## Steps to reproduce
click of all of option in section of What could be affected? page
continue to reach to the review report page

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
We should just use Phil's conjunction code, I think it's used for the "How did the incident start" sentence
