### ISSUE TITLE
Same issue as #1249 happened when the user click on "Create a new report"

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1319]
## Summary

When the user completed and submitted a report, the user wants to another report by click on "Create a new report", the data in the previous report is still displayed. 

## Steps to reproduce
Enter required info and submit a report
At thank you page, click on "Create a new Report"
Expected Result:  The pages should be reset
Actual Result: The data in previous report is still displayed  

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by khalidelaggan** [comment]
More than happy to take on this task

**Comment by sastels** [comment]
We should probably just clear the data when the user goes the the landing page

**Comment by DianeLiu2019** [comment]
issue fixed associated with   PR #1386
