### ISSUE TITLE
Client-side validation: File upload specs (Correct file number, format, and size)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#1328]
## Summary

We are starting by accepting the same types of files as CAFC.

This means:
- accepting 3 files maximum.
- maximum file size is 4MB.
- supported extensions include: .png, .jpg, .jpeg, .doc, .dox, .xls, .xlsx, .pdf, and .txt

Can we prevent people from choosing files of bigger size or of different file format?
And can we add a message when they reach the maximum number of files

## Design Detail 

https://www.figma.com/file/R054FzUOrpP13oTbMsQevj/Sprint-5?node-id=1984%3A0

<img width="285" alt="Screen Shot 2020-02-07 at 4 06 48 PM" src="https://user-images.githubusercontent.com/38330843/74065886-e48b3480-49c3-11ea-8f34-f6930b7fa6e9.png">

<img width="289" alt="Screen Shot 2020-02-07 at 4 06 59 PM" src="https://user-images.githubusercontent.com/38330843/74065892-e81ebb80-49c3-11ea-8935-4208a3c5efb7.png">

**Comment by ngosset** [comment]
https://github.com/cds-snc/report-a-cybercrime/issues/1256

@naomiseminega @anikbrazeau 

Duplicate issue here - Or shall we say one issue is for design and client side validation and one issue is for server side validation?

**Comment by anikbrazeau** [comment]
Thanks for linking these issues! 👍 
Perhaps we keep this one open for the message that appears once 3 files are added?

**Comment by naomiseminega** [comment]
Sounds good! We can keep this one as client-side validation.

**Comment by anikbrazeau** [comment]
I've attempted to add some of the specs into the copy. Do you think this works? Does the functionality also prevent users from being able to add files that are outside the file types, size and number?

<img width="207" alt="Screen Shot 2020-02-12 at 10 25 23 AM" src="https://user-images.githubusercontent.com/38330843/74349476-4f50bd00-4d82-11ea-8b61-f87470d44f13.png">

<img width="209" alt="Screen Shot 2020-02-12 at 10 25 17 AM" src="https://user-images.githubusercontent.com/38330843/74349483-5081ea00-4d82-11ea-8620-96c00b4e2005.png">

<img width="209" alt="Screen Shot 2020-02-12 at 10 26 17 AM" src="https://user-images.githubusercontent.com/38330843/74349503-57106180-4d82-11ea-94ef-42093857e6d2.png">

<img width="206" alt="Screen Shot 2020-02-12 at 10 26 10 AM" src="https://user-images.githubusercontent.com/38330843/74349509-58418e80-4d82-11ea-83a7-7e31d75c93c2.png">

<img width="164" alt="Screen Shot 2020-02-12 at 10 26 33 AM" src="https://user-images.githubusercontent.com/38330843/74349530-60013300-4d82-11ea-99a4-10da4b59efac.png">

<img width="168" alt="Screen Shot 2020-02-12 at 10 26 27 AM" src="https://user-images.githubusercontent.com/38330843/74349534-6099c980-4d82-11ea-9f32-86f173868d4c.png">

**Comment by anikbrazeau** [comment]
## ADDITIONAL TEXT 

### **1. When no files are attached**

Above "Add file" button:
- **EN**  You can add a maximum of 3 files, each up to 4 MB in size.
- **FR** Vous pouvez ajouter un maximum de 3 fichiers, chacun d’une taille maximale de 4 MB.

Below "Add file" button:
- **EN** Supported file types: .png, .jpeg, .doc, .xls, .pdf, and .txt.
- **FR** Types de fichiers supportés : .png, .jpeg, .doc, .xls, .pdf, and .txt.

Blue box: 
- **EN** Files will be checked for safe content.
- **FR** Les fichiers seront vérifiés pour s’assurer que leur contenu est approprié.

### **2. When 1-2 files are attached**

Above "Add file" button:
- **EN**  # files attached
- **FR** # fichiers joints

Below "Add file" button:
- **EN** Supported file types: .png, .jpeg, .doc, .xls, .pdf, and .txt.
- **FR** Types de fichiers supportés : .png, .jpeg, .doc, .xls, .pdf, and .txt.

Blue box: 
- **EN** Files will be checked for safe content.
- **FR** Les fichiers seront vérifiés pour s’assurer que leur contenu est approprié.

### **3. When 3 files are attached**

No "Add file" button

Blue box: 
- **EN** You have added the maximum number of files allowed.
- **FR** Vous avez ajouté le nombre maximum de fichiers possibles.
