### ISSUE TITLE
Rename database labels to correspond with data entered

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#1342]
## Summary

Rename data labels to be more descriptive:

1. victim info should be labelled as such to not be confused with suspect
ex: "contactInfo.email" --> should include victim --> victim.email
	
2. suspect info should be labelled as such to not be confused with suspect
ex: "howdiditstart.howDidTheyReachYou.email" --> should include suspect --> suspect.email

3. Suspect clues labels should be more specific 
 - "suspectClues.suspectClues" --> suspectClues.suspectName
 - "suspectClues.suspectClues2" --> suspectClues.suspectAddress
 - "suspectClues.suspectClues3" --> suspectClues.otherDetails

## Motivation

This will make it easier to decipher the data we receive.

## Unresolved questions

This will be used for the email we send to analysts. Depending when this is done it could touch that content.

**Comment by ngosset** [comment]
This issue is from before our first release. This made more sense when we were just e-mailing out the JSON, but now that we have a nicely formatted report it's not a very high priority issue and risks breaking a lot of things if it's not done carefully.
