### ISSUE TITLE
Update contact details page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#1363]
## Summary

Update with full name and phone number.

## Design Detail

https://www.figma.com/file/R054FzUOrpP13oTbMsQevj/Sprint-5?node-id=2067%3A4933

![Screen Shot 2020-02-12 at 1 59 48 PM](https://user-images.githubusercontent.com/38330843/74367506-00198500-4da0-11ea-894d-8cda7fad4b40.png)

![Screen Shot 2020-02-12 at 1 59 39 PM](https://user-images.githubusercontent.com/38330843/74367507-00b21b80-4da0-11ea-8ccf-e0d8e5f16606.png)

**Comment by amazingphilippe** [comment]
Fixed in #1356
