### ISSUE TITLE
The "Report now" and "Call now" button on IE are not aligned as Google Chrome

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1370]
## Summary

The "Report now" and "Call now" button on IE are not aligned as Google Chrome

## Design Detail

Please see the attached file

![buttonNotAlign](https://user-images.githubusercontent.com/60269104/74440598-42909f80-4e3c-11ea-9f13-73a4e76c5521.jpg)

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by DianeLiu2019** [comment]
see PR# 1542:  change to list the landing box horizontally instead. this  issue closed
