### ISSUE TITLE
No empty line between contact and version on IE

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1371]
## Summary

No empty line between contact and version on IE but it does has on the Google Chrome

## Design Detail
![feedback](https://user-images.githubusercontent.com/60269104/74443470-3e1ab580-4e41-11ea-936f-d1b1d7769793.jpg)

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by DianeLiu2019** [comment]
see PR# 1542  change to list the landing box horizontally instead. the issue closed

**Comment by anikbrazeau** [comment]
Is this page in the flow? What is the link?

I think it's been replaced by : https://report-a-scam.cds-snc.ca/finalFeedback
