### ISSUE TITLE
App broken in French (!!!)

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#1374]
## Summary

Clicking "Commencer le rapport" leads to a blank screen.

## Steps to reproduce

Click "Commencer le rapport" on second page

**Comment by sastels** [comment]
might be google analytics related. Chrome showed GA code after the crash 🤷‍♂

**Comment by anikbrazeau** [comment]
Seems inconsistent? 
Working @ 4 pm Feb 13?

**Comment by kevinyang06** [comment]
it works now

**Comment by sastels** [comment]
Let's close this for now. But on Monday and Friday next week let's do a full walkthrough on IE to make sure there's (hopefully) nothing that'll bite us in the ass when we launch.
