### ISSUE TITLE
IE 11 - Rendering issue

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1380]
## Summary

When the user launches the application and switch it to french, the rendering issue will happen. It is intermittent issue and cannot be reproduced

The work around is to closed the IE browser and open it again. The issue will be gone 
![error](https://user-images.githubusercontent.com/60269104/74459299-0f103e00-4e59-11ea-89fd-5324fa489b48.png)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by amazingphilippe** [comment]
Isn't this google chrome?

**Comment by lmcbhvu** [comment]
No, it happened on IE

**Comment by sastels** [comment]
fixed when we got rid of those gray boxes.
