### ISSUE TITLE
Final feedback page after submit

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/report-a-cybercrime#1381]
## Summary

We have a dedicated page for final feedback form after being submitted, but we don't have content for this page.

Can we redirect to the Report Thank you page, while returning a "thank you for helping us" banner?

## Design Detail

~~A design is not created for this~~
Just route back to the thank you page for now

## Unresolved questions

Would still suggest to return to the report's thank you page, while we figure out the design of this.

**Comment by anikbrazeau** [comment]
Link to #1304
