### ISSUE TITLE
Broken links on front page

### ISSUE THREAD

**Issue by ngosset** [cds-snc/report-a-cybercrime#1388]
## Summary

The "Call Now" link on our first page broke after CAFC launched their redesign.

## Steps to reproduce
Click "Call Now" on this screen:

![screen1](https://user-images.githubusercontent.com/2212291/74490328-39ccb780-4e96-11ea-9386-4ae3a061e9a0.png)

Get this error:

![screen2](https://user-images.githubusercontent.com/2212291/74490316-2e798c00-4e96-11ea-945d-0995492172d9.png)

## Unresolved questions

Unrelated, are we going to have a "You can still opt-out and report the old way if you want" type link? I vaguely recall telling CAFC we would do this.

**Comment by anikbrazeau** [comment]
Could we link it to call directly instead? (aka click to call)
https://developers.google.com/web/fundamentals/native-hardware/click-to-call

As for the question about CAFC opt-out: we've put a link back to the FRS in the Beta banner now.

**Comment by ngosset** [comment]
> Could we link it to call directly instead? (aka click to call)
> https://developers.google.com/web/fundamentals/native-hardware/click-to-call
> 
> As for the question about CAFC opt-out: we've put a link back to the FRS in the Beta banner now.

Sounds like a good idea to me. And the opt-out link in the beta banner already re-directs to the right page so no need to also have the "Call Now" link also redirect.

**Comment by sastels** [comment]
Seems to work for me now - I go to
<img width="974" alt="image" src="https://user-images.githubusercontent.com/8228248/74560938-992dd480-4f35-11ea-9f52-b28e4debb5b4.png">

**Comment by ngosset** [comment]
> Seems to work for me now - I go to


Looks to me like New Media added a redirect when you go to the old .htm, so it sends you to the new one. We should still probably update our hyperlink.

**Comment by ngosset** [comment]
> > Seems to work for me now - I go to
> 
> Looks to me like New Media added a redirect when you go to the old .htm, so it sends you to the new one. We should still probably update our hyperlink.

That said - if it's working now I think we can remove the 'need for launch'

**Comment by anikbrazeau** [comment]
Fixed in #1399
