### ISSUE TITLE
Should it go back to previous page when the user clicks on <Go back> option

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1396]
## Summary

When the user clicks on <go back> option, it should go the previous page

## Steps to reproduce

1. The user enter the info
Start at incident page -> What could be affected page -> How was your personal info affects page -> What happened page
2. At What happened page, the user clicks on <go back> option
Expected result: It should go to "How was your personal info affects" page 
Actual result:  It goes to "What could be affected " page

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by anikbrazeau** [comment]
Link to #1258
