### ISSUE TITLE
Missing attached file in the database

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1408]
## Summary

Missing attached file and description in the database

## Steps to reproduce

1. Fill out the report
2. Attached file and description 
Expected Result: The attached file and description  should be included in the database
Actual Result: The attached file and description are missing in the database

![fileAttached](https://user-images.githubusercontent.com/60269104/74656947-3b7bd100-515d-11ea-8bdb-29f75148bc75.jpg)

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
Now there when submitting via Firefox:
<img width="515" alt="image" src="https://user-images.githubusercontent.com/8228248/74768384-7a418200-5256-11ea-830e-938965715fc1.png">

**Comment by sastels** [comment]
working now
