### ISSUE TITLE
Should remove "Location" field in the database

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1409]
## Summary

With a currently version, the location is removed from "Enter your location" page. Should the location be removed as well in the database?
![location](https://user-images.githubusercontent.com/60269104/74657180-af1dde00-515d-11ea-9c5c-4ca0ec87bfa5.jpg)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
working now
