### ISSUE TITLE
Missing the info on "Tell us more"  section of review report page

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1412]
## Summary

No information on section "Tell us more" on review report page is found on the database

## Steps to reproduce

Enter some text in section "tell us more" at review report page

![info](https://user-images.githubusercontent.com/60269104/74662129-4fc4cb80-5167-11ea-9a16-68d8530ca2a0.jpg)

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
We have removed that input from the Confirmation page.
