### ISSUE TITLE
Bug: Server error gets printed in the 'reference number field' on the Thank You Page

### ISSUE THREAD

**Issue by naomiseminega** [cds-snc/report-a-cybercrime#1421]
## Summary
If you go through the App (whether running on server or dev), and submit the report, the latest server error will be printed in green box at the top of the Thank you Page after the 'Your reference number is ' field.

## Steps to reproduce
- Navigate to localhost:3000
- Go through the App (adding dummy info is optional)
- Submit report, and check the green box at the top of the Thank you page 
- Do Fn F12 and compare the printed message to the most recent server error.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by naomiseminega** [comment]
<img width="1386" alt="Screen Shot 2020-02-17 at 12 44 42 PM" src="https://user-images.githubusercontent.com/58989481/74676754-bb696180-5184-11ea-999e-1a579fa8b0e1.png">

**Comment by naomiseminega** [comment]
@sastels  I can close this bug right? It will be fixed by Norm's upcoming PR. Seems like the same bug Emily got.

**Comment by sastels** [comment]
Yeah, I think so. 👍
