### ISSUE TITLE
Links in Footer always link to EN Privacy Statement and EN Terms&Conditions even in FR

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#1430]
## Summary

Going through the app in French and clicking on the links in the footer leads to English pages for both "Avis" and "Confidentialité"

<img width="212" alt="Screen Shot 2020-02-18 at 12 16 30 PM" src="https://user-images.githubusercontent.com/38330843/74760656-be2d8a80-5248-11ea-986a-312d86221b67.png">

**Comment by ngosset** [comment]
Going to fix this by adding queryParm support eg. (.htm?lang=en))

**Comment by anikbrazeau** [comment]
This is also the case on the links to the Privacy statement on the 'Privacy and consent' page and on the 'Terms and Conditions' page.

![Screen Shot 2020-02-20 at 9 06 04 AM](https://user-images.githubusercontent.com/38330843/74940975-46826b80-53c0-11ea-86a9-43c9416faa50.png)

![Screen Shot 2020-02-20 at 9 06 13 AM](https://user-images.githubusercontent.com/38330843/74940979-484c2f00-53c0-11ea-8665-f74135b0bb78.png)
