### ISSUE TITLE
Close mid-service feedback when switching pages or submitting.

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#1434]
## Summary

Mid-service feedback stays open when navigating the site.

## Steps to reproduce

1. click on "Is there something wrong on this page?"
2. click continue

<img width="454" alt="Screen Shot 2020-02-18 at 2 27 44 PM" src="https://user-images.githubusercontent.com/38330843/74770792-f2aa4200-525a-11ea-8546-dceac0bfa2a5.png">

**Comment by sastels** [comment]
It’s because the midfeedback component is in App, not one of the pages in Home, so it doesn’t change when the page changes. If we move it onto every page then we should be good.

**Comment by sastels** [comment]
We should probably have some sort of PageLayout component that every page starts with, and contains the feedback and probably other things.
