### ISSUE TITLE
"Other" doesn't appear in Summary sentences

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#1452]
## Summary

Sentence on confirmation page does not fill in "Other" if left unspecified.
Sentence also needs a period at the end in both FR and EN.

![Screen Shot 2020-02-19 at 3 10 19 PM](https://user-images.githubusercontent.com/38330843/74871821-1f795a80-532a-11ea-82bc-465a10ff3c16.png)

![Screen Shot 2020-02-19 at 3 10 03 PM](https://user-images.githubusercontent.com/38330843/74871818-1ee0c400-532a-11ea-950a-680d7eddbb0f.png)

![Screen Shot 2020-02-19 at 3 10 14 PM](https://user-images.githubusercontent.com/38330843/74871815-1daf9700-532a-11ea-820f-71894eec82e5.png)

![Screen Shot 2020-02-19 at 3 10 08 PM](https://user-images.githubusercontent.com/38330843/74871817-1e482d80-532a-11ea-9364-f0f6541555d6.png)

## Steps to reproduce

Check all the boxes.
Don't enter anything in other.
Go to review page.

**Comment by anikbrazeau** [comment]
Link to #1470

**Comment by sastels** [comment]
duplicate of #1470
