### ISSUE TITLE
IE: Text is overwritten  on the homepage of report

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1467]
## Summary

Text is overwritten  on the homepage of report on IE browser

## Steps to reproduce

![error6](https://user-images.githubusercontent.com/60269104/74895822-b234ec00-5360-11ea-869f-ee1719819c65.jpg)

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by lmcbhvu** [comment]
Get the same issue as figure 2 (text is overwritten on each other) regardless the window IE is maximized or minimized (in both French and English)

**Comment by khalidelaggan** [comment]
https://github.com/cds-snc/report-a-cybercrime/pull/1542 will take care of this issue as well 
<img width="795" alt="Screen Shot 2020-02-24 at 8 18 34 PM" src="https://user-images.githubusercontent.com/2603117/75207017-a1f88480-5745-11ea-998a-f0fcde1a1e94.png">
