### ISSUE TITLE
"Is something wrong on this Page?" section is always displayed and cannot be closed on IE and Firefox

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1468]
## Summary

"Is something wrong on this Page?" section is always displayed and cannot be closed on IE and Firefox

## Steps to reproduce

![error5](https://user-images.githubusercontent.com/60269104/74896586-a77b5680-5362-11ea-871c-4a07edb4fd3a.jpg)

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by amazingphilippe** [comment]
Not compatible on IE: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

Chakra's collapse stuff not working either: https://chakra-ui.com/collapse

We can use a control box with an input like our progressive disclosure fields (But this would be major wonkiness)

✨✨✨We can use a polyfill like this: https://github.com/rstacruz/details-polyfill ✨✨✨
