### ISSUE TITLE
Missing the word "Other" in the some section of summary page

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1470]
## Summary

Missing the word "Other" in the some section of summary page

## Steps to reproduce

![error](https://user-images.githubusercontent.com/60269104/74897954-83217900-5366-11ea-843a-6ad61a873386.png)

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by anikbrazeau** [comment]
Link to #1452

**Comment by sastels** [comment]
"How did it start" done in #1495
