### ISSUE TITLE
Should we add the validation on the transaction date, postal and phone?

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1471]
## Summary

Should we add the validation on the transaction date (to prevent the user to enter the future date), postal (enter the wrong format) and phone (enter the letter instead of number)?

## Design Detail

> Explain the design in enough detail for somebody familiar with the infrastructure to understand. This should get into specifics and corner-cases, and include examples of how the service is used. Any new terminology should be defined here.

> Include an image of any old vs new design changes if possible

> include links to figma or other design designs if possible

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by naomiseminega** [comment]
Linking issue #1463

**Comment by sastels** [comment]
Decided yes, and broken into smaller issues.
