### ISSUE TITLE
<ReportID> is displayed on thank you page

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1472]
## Summary

<ReportID> is displayed on thank you page

![error](https://user-images.githubusercontent.com/60269104/74898660-8ae21d00-5368-11ea-9cb5-59482c4f33f8.jpg)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
We should display something like "Submitting your report..." for that sentence, and when the data returns, if it's NOT a report id (ie starts with "NCFRS" then display something like "I'm sorry, your report was not successfully submitted. Please come back later"
