### ISSUE TITLE
The ">" is displayed in the second line in all of buttons

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1474]
![error4](https://user-images.githubusercontent.com/60269104/74900055-96cfde00-536c-11ea-94de-a122a66d3e60.jpg)
## Summary

The ">" is displayed in the second line in all of buttons. It happened only on Firefox browser

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by amazingphilippe** [comment]
@lmcbhvu Do you know which version of firefox? I want to figure out if it's an issue with flexbox

**Comment by lmcbhvu** [comment]
The Firefox on my LP is 43.0.1 but it works fine with Norm's LP. His Firefox version is 73.0.1

**Comment by amazingphilippe** [comment]
This is a know Flexbug: [Flexbug # 9](https://github.com/philipwalton/flexbugs#flexbug-9) Buttons can't be flex containers.
