### ISSUE TITLE
Validation for dates

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#1479]
## Summary

Date on when did it start page
Transaction date on money page

## Design Detail

Day = numbers only, 1-30, reformat 1 to 01
Month = numbers (or type month name?), 1-12, reformat 1 to 01
Year = numbers only, 1900-present

**Comment by amazingphilippe** [comment]
@sastels I suggest holding off on any validation until we merge #1510 
We could avoid having to reformat validation conditions
