### ISSUE TITLE
Missing the information about what did they ask on summary page

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1502]
## Summary

Missing the information about what did they ask on summary page

## Steps to reproduce

![error](https://user-images.githubusercontent.com/60269104/75037769-f15b5e00-5482-11ea-9af5-59c8227615a2.jpg)

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
fixed in #1501
