### ISSUE TITLE
No info on how did the incident start section of summary page

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1504]
## Summary

No info on how did the incident start section of summary page if the victim did not choose any option on how did the suspect reach you

## Steps to reproduce

![error](https://user-images.githubusercontent.com/60269104/75038509-7d21ba00-5484-11ea-9118-b24ee123d24b.jpg)

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
fixed in #1501
