### ISSUE TITLE
Cannot start the report on safari browser (only mini-ipad)

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1518]
## Summary

Cannot fill out the report on Safari browser (Ipad)

## Steps to reproduce

![safari](https://user-images.githubusercontent.com/60269104/75086937-1b0a9880-5508-11ea-9cea-9e408a7de436.jpg)

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
Do you know which iPad and version of iOS it has? Using BrowserStack I see:
* works: iPad Gen 7, iOS 13
* works: iPad Mini 2019, iOS 12
* works: iPad Mini 4 with iOS 11
* works: iPad Gen 5, iOS 11
* doesn't work: iPhone 7 Plus, iOS 10 (Simulator)
* doesn't work: iPhone 6s Plus, iOS 9
* doesn't work: iPad Mini 3, iOS 8
* doesn't work: iPad Air 2, iOS 8

It's possible that those Grey boxes on the landing page use a feature that only works on iOS 11 and up.
I did manage to click the link and the other pages looked correct, just those grey boxes on the landing page were wonky.

**Comment by lmcbhvu** [comment]
The mini Ipad that I used is mini ipad 2, original iOS7.0 and update to iOS 10

**Comment by khalidelaggan** [comment]
@amazingphilippe @sastels I'm confident this PR https://github.com/cds-snc/report-a-cybercrime/pull/1542 will fix this issue as well

**Comment by khalidelaggan** [comment]
<img width="795" alt="Screen Shot 2020-02-24 at 8 18 34 PM" src="https://user-images.githubusercontent.com/2603117/75206827-429a7480-5745-11ea-9b23-d6ee0551a230.png">
