### ISSUE TITLE
Call now or report now button are outside the box

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1527]
## Summary

Call now or report now button in French are outside the box. It looks OK only when you are maximum size of window (but not safari and IE)

## Steps to reproduce

![error](https://user-images.githubusercontent.com/60269104/75119984-ce34d800-5655-11ea-9504-4fdf3921b855.jpg)

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by anikbrazeau** [comment]
We could possibly shorten to "Signaler" and "Appeler" in the interim of a fix ?

**Comment by khalidelaggan** [comment]
PR to fix this is now added to the queue

**Comment by khalidelaggan** [comment]
<img width="795" alt="Screen Shot 2020-02-24 at 8 18 34 PM" src="https://user-images.githubusercontent.com/2603117/75206603-d28bee80-5744-11ea-8988-6dcb26b5f42d.png">
