### ISSUE TITLE
Date on the analyst report

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1529]
## Summary

1. If the victim does not enter any date, we should use the same format to display the date (occurrence date and the transaction date).
2. Should we remove the tranactionDate in the extra field because I think that date is the same date of  financial transaction section.

## Steps to reproduce

![Date](https://user-images.githubusercontent.com/60269104/75126554-7ebbcf80-5688-11ea-9788-551476440f93.jpg)

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
fixed in release candidate.
