### ISSUE TITLE
Add more try...catch's to server code

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#1533]
## Summary

It would be good to wrap more of the server code in `try...catch`'s so that if some strange error happens it'll get console.log'd and the server can continue.

## Motivation

Make the code more robust - if one part fails the rest will run.

**Comment by khalidelaggan** [comment]
Would it be possible to change this to a high priority? A part of getting the e2e running in CI before launch will require a few of these fixes.

Thanks!
