### ISSUE TITLE
Add some sort of "This app is best viewed with Firefox or Chrome" to landing page

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#1538]
## Summary

because our IE support is not great

**Comment by amazingphilippe** [comment]
Not compatible on IE: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

Chakra's collapse stuff not working either: https://chakra-ui.com/collapse

We can use a control box with in input like our progressive disclosure fields (But this would be major wonkiness)

✨✨✨We can use a polyfill like this: https://github.com/rstacruz/details-polyfill ✨✨✨

**Comment by anikbrazeau** [comment]
We can put this as a temporary band-aid solution, keeping in mind that we should remove this caveat text once we sort out issues in other browsers.

**Comment by anikbrazeau** [comment]
Copy could be something like this:

**EN:** This website is best viewed on Firefox or Google Chrome web browsers.
**FR:** Ce site This website est optimisé pour les navigateurs Firefox et Google Chrome.

**Comment by khalidelaggan** [comment]
@anikbrazeau Where would be the best spot to add this alert?

**Comment by sastels** [comment]
@anikbrazeau and @DianeLiu2019 added it near the top in #1541
