### ISSUE TITLE
Remove transactionDate field from react app

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1565]
## Summary

The extra fields in the analyst report should be removed because those info are included in other section.

## Steps to reproduce

![info](https://user-images.githubusercontent.com/60269104/75353603-b342ad80-5879-11ea-967d-bdeca77e99e7.jpg)

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
We want to leave these fields printing here - it's a check that we haven't added or changed fields in the app that somehow do not make it to the analyst. Essentially, every field we show to the analyst isn't printed in this "missing" section.

In this case, it's showing that the app is sending a `transactionDate` field. This was used before we switched to separate day/month/year fields, but apparently there is still an empty `transactionDate` field being sent. We should delete that field from the app, and then there will be no missing fields so there will be no "missing field" section to the analyst report.

**Comment by sastels** [comment]
Also - around line 55 of `ConfirmationPage.js` and line 44 of `ConfirmationSummary.js` we should set `transactionDay`, `transactionMonth`, and `transactionYear` to `''`
