### ISSUE TITLE
Send files and report as a single e-mail

### ISSUE THREAD

**Issue by ngosset** [cds-snc/report-a-cybercrime#1579]
## Summary

Files are sent as a separate e-mail. This is a problem as files can come in out of order and it's not clear which report they are from. We should try to send everything as one e-mail.

## Motivation

This is also important because an offensive image could be received by the analyst before they see the report that has a warning image might be offensive

## Unresolved questions

Additionally: Can we make the warning about potential offensive image more apparent (bigger font or part of the subject?)

**Comment by sastels** [comment]
It’s unlikely this will be done by Monday - what about if we just don’t send files that fail CM?

**Comment by davidheerema** [comment]
If we / @kevinyang06 can complete a PR for adding a subject to emails, the emails themselves can say "attachment for report number x" or something like that which could protect analysts that way.

At this point, whatever is simplest for Monday.

**Comment by davidheerema** [comment]
I don't think sending emails as a single email is need for launch, but adding a subject or not sending files that are CM should be...

Right now I don't know (forget) if the attachment names themselves even match what the report email lists them as.

**Comment by sastels** [comment]
Given that we are adding appropriate subjects to the emails, do we still need a single email? if so, shoulod it be a lower priority? @ngosset
