### ISSUE TITLE
It skips "Several times" and "I'm not sure" button when the user uses <tab>

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1583]
## Summary

In "when the incident start"page, if the user use the tab to move from one option to the option, it moves directly from "Once" to "continue" button (skipping "Several times" and "I'm not sure" button)

## Steps to reproduce

- Go to "when the incident start"page
- use tab to move

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
I believe this is the required behaviour. From
https://www.w3.org/wiki/RadioButton
>  The Tab key moves focus between radio button groups and other widgets.

> Up Arrow and Down Arrow keys move focus and selection. 

@khalidelaggan @amazingphilippe thoughts?

**Comment by amazingphilippe** [comment]
> https://www.w3.org/wiki/RadioButton

Expected behaviour
