### ISSUE TITLE
Add subject for encrypted analyst report email

### ISSUE THREAD

**Issue by kevinyang06** [cds-snc/report-a-cybercrime#1585]
## Summary

currently there is no subject for encrypted email.

## Design Detail

> 

> Include an image of any old vs new design changes if possible
![image](https://user-images.githubusercontent.com/58781425/75456053-0c791280-5948-11ea-8ec1-7ba67d053b30.png)

> include links to figma or other design designs if possible

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by davidheerema** [comment]
There should be a subject (it would be nice if it was different subject slightly, with same report number) added to both the report email and the attachment emails.
