### ISSUE TITLE
Clean up logs

### ISSUE THREAD

**Issue by davidheerema** [cds-snc/report-a-cybercrime#1587]
In Azure, all Console logging is aggregated and collected in Log Analytics database.  This is the log store where alerts and queries are scheduled against log entries to create alarms etc.

It seems that the current system console logging will create multiple log entries for a multi-line logical log entry.  I have attached a screenshot for clarity.

You can imagine how this will make operational support difficult and troubleshooting very difficult as well.
![Screen Shot 2020-02-27 at 9 59 44 AM](https://user-images.githubusercontent.com/51758091/75456772-f3249600-5948-11ea-9b8b-983cd6b9dce4.png)

**Comment by sastels** [comment]
I think there's a lot in there that has been mainly diagnostic - at this point we could either delete or comment out, just mainly keeping warnings and errors.

**Comment by davidheerema** [comment]
Steve, I actually find that the level of logging is nice right now from a support perspective.  You can trace nicely through what a transaction is doing.

I am talking specifically about the line output - for one entry (echoing json, which is kind of useful in some cases) it would be nice to use a more azure log analytics friendly format, if at possible of course.

I can help investigate when I have time.
