### ISSUE TITLE
Confuse info on the thank you page when the victim cancels the report and gives feedback

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1592]
## Summary

When the victim cancels the report and fills out the feed back, it should go back to "Thank you for trying our new website" page and with an extra sentence "Thank you. We have received your feedback." instead of "Thank you for reporting" with sentence  "Submitting your report…" because the victim has not submitted any report yet

## Steps to reproduce

- Fill out a few pages of report
- Click "Cancel"
- Click "Cancel Report"
- Click " Tell us more"
- Fill out the form and click submit

![cancel](https://user-images.githubusercontent.com/60269104/75488355-2df4f100-597e-11ea-8ff9-9094709c534f.jpg)

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by davidheerema** [comment]
I don't think this issue is [Need for Launch] priority.
