### ISSUE TITLE
Tag your releases after you incorporate user feedback

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/report-a-cybercrime#160]
@danprime - Our friends in policy would like to measure how often we incorporate user feedback in our code. One way we can easily do this is everytime we include a feature based on user-feedback we cut another release on GitHub. We did this in VAC (https://github.com/veteransaffairscanada/vac-benefits-directory/releases) and it would be great if we could get a start on this with RCMP as well. Please let me know if you have questions or concerns.

**Comment by maxneuvians** [comment]
Better idea - tag issues with a "User feedback" label and then we can track the metric much better!

**Comment by sleepycat** [comment]
Good idea. We'll start using that "user feedback" label for upcoming development.
