### ISSUE TITLE
The user should not receive the confirmation if there is some error in the report

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1603]
## Summary

If there is an error in the report, the user should not receive the confirmation number and the report which contains an error should not be saved in our database

## Steps to reproduce

To make it 's easy to reproduce, here is the steps
1. Launch the report and proceed to How the incident start page
2, Bookmark that page
3. Open a new browser and open the bookmark 
4. Start to submit a report from the How the incident start page

![errorInReport](https://user-images.githubusercontent.com/60269104/75573753-7ae2d100-5a2b-11ea-8c38-95fdd98ff299.jpg)

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
In the current (release) app it is not possible to navigate directly to anything except the landing page (including if you are going from a bookmark). This was just added yesterday.
