### ISSUE TITLE
Should go to the same page if the user clicks on "Royal Canadian Mounted Police" link

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1611]
## Summary

It should go to the same page if the user clicks on "Royal Canadian Mounted Police" link from report homepage or Privacy statement page

If the user licks on "Royal Canadian Mounted Police" link from report homepage, it will open The National Cybercrime Coordination Unit (NC3) page 

![NC3](https://user-images.githubusercontent.com/60269104/75709957-b252b700-5c91-11ea-872c-d33bf3d5368c.jpg)

If the user licks on "Royal Canadian Mounted Police" link from Privacy statement page, it will open homepage of RCMP

![RCMP](https://user-images.githubusercontent.com/60269104/75709972-b7176b00-5c91-11ea-97d5-326166ed62ca.jpg)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
@anikbrazeau any thoughts as to which one we want?

**Comment by lmcbhvu** [comment]
I think it should go RCMP home page

**Comment by anikbrazeau** [comment]
I think this is fine as is??

**Royal Canadian Mounted Police** should link to http://www.rcmp-grc.gc.ca/en/home

**National Cybercrime Coordination Unit** should link to http://www.rcmp-grc.gc.ca/en/the-national-cybercrime-coordination-unit-nc3

**Comment by sastels** [comment]
I think the issue is that on the landing page we have "Your report helps the Royal Canadian Mounted Police and..." and the "Royal Canadian Mounted Police" links to NC3 instead of the RCMP home page.

**Comment by sastels** [comment]
As discussed IRL with Steph, we think we want to keep the links as they are. In particular, we want the link on the landing page to go to NC3, but we want to keep the content simple (ie labelling the link just as RCMP rather than the more precise NC3)
