### ISSUE TITLE
Missing "Other" option in What could be affected in the report ---Please confirm with Anik first before fixing the issue

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1623]
## Summary

Missing "Other" option in What could be affected in the report 

## Steps to reproduce

- Launch the application and fill out the form
- Choose "Other" at "What could be affected" page

Actual Result: Nothing see the report which is sent to analyst

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by DianeLiu2019** [comment]
talked to Anik before, she mentioned victim will input other information on whathappened page, so we don't want victim input other  information in whatwasaffected page

**Comment by sastels** [comment]
as discussed IRL the correct design is what we think is correct - but we should ensure that users feel the same way. Closing for now.
