### ISSUE TITLE
Make "Warning / Prototype" banner more distracting

### ISSUE THREAD

**Issue by davidheerema** [cds-snc/report-a-cybercrime#1627]
Since every environment for the application is online (DEV, Staging, PROD) I feel that it would be best to make the warning banners more distracting / evident.  Something that will make it impossible to mistake for a PROD site, for both users, support staff, and testers.

**Comment by amazingphilippe** [comment]
We can do something like this

- Make sure we have distinct colors

<img width="550" alt="Screen Shot 2020-03-10 at 1 23 51 PM" src="https://user-images.githubusercontent.com/5230720/76340690-65469480-62d2-11ea-8a37-a7e7d45c57c6.png">

**Comment by amazingphilippe** [comment]
Because no one is supposed to see these banners, we could just make them super tall. Around 400px or something like that

**Comment by davidheerema** [comment]
Sounds lovely!
