### ISSUE TITLE
after submit report, go to Thank you page, victim hit back in the browser. it is better going back to landing page 

### ISSUE THREAD

**Issue by DianeLiu2019** [cds-snc/report-a-cybercrime#1630]
## Suggestion / question
after submit report, go to Thank you page, victim hit back in the browser. it is better going back to landing page instead of Confirmation page.

**Comment by stephaniemgauthier** [comment]
I agree. Currently it goes back to the review page. Then if user hits submit page a new NCFRS number is generated.

**Comment by DianeLiu2019** [comment]
Team decided to use another way to stop  victim submit the report again. see PR #1683
