### ISSUE TITLE
Out of order HRMIS IDs will encrypt for the wrong email.

### ISSUE THREAD

**Issue by davidheerema** [cds-snc/report-a-cybercrime#1633]
Regarding the environment variables:

> comma delimited list of HRMIS should be same order as comma delimited list of e-mail
- Norm

If they are out of order then people will receive emails encrypted for others.  I think a repair could be to use the HRMIS to lookup the email in LDAP, or some other creative solution.

Another solution would be to encrypt the mime messages once, for all recipients, and then draft one email, to all recipients.

**Comment by sastels** [comment]
👍 sending one email encrypted for everyone would be the best solution. Though if we can get the email address from ldap then the config would be even simpler.

**Comment by davidheerema** [comment]
We can get the email from there.  So eventually one email with config that
looks up email based on HRMIS
