### ISSUE TITLE
File upload button target is smaller than the button itself

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/report-a-cybercrime#1649]
## Summary

Clicking in the padding of the button does not activate the file upload button

## Steps to reproduce

1. On evidence page
2. Click in the blue padding of the button
3. Nothing happens
4. Click on the word 'upload'
5. File selection window opens
![ezgif-2-7160782b7829](https://user-images.githubusercontent.com/5230720/76330634-77b9d180-62c4-11ea-965b-d805239c1c55.gif)

**Comment by sastels** [comment]
Also clicking on the paper clip does nothing - has to be on the text.

**Comment by sastels** [comment]
I think it's because our file upload button has the input button inside it? so clicking on the outside button doesn't do anything.

```javascript
   <Button
      {...props}
      as="div"
      _focusWithin={{
        boxShadow: 'outline',
      }}
    >
      <VisuallyHidden
        as="input"
        type="file"
        id="uploader"
        name="uploader"
        accept=".png, .jpg, .jpeg, .doc, .docx, .xls, .xlsx, .pdf, .txt, .rtf"
        max-upload={3}
        onChange={onChange}
      />
      <Label htmlFor="uploader">{props.children}</Label>
    </Button>
```
