### ISSUE TITLE
(Outlook) The French text in analyst report is not displayed correctly with special characters 

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1652]
## Summary

In outlook, The French text in analyst report is not displayed correctly with special characters 
Here is example

What happened:           B+Ce n'est pas normal. C'est une anomalie de ne pas considC)rer les femmes pour des postes importants. Moi, j'aimerais entendre ces associations sportives venir de l'avant et nous expliquer le pourquoi. Il y a peut-C*tre une bonne raison qu'on ne connaC.t pas, mais dites-nous-la et on va finir par comprendre. Mais je ne pense pas qu'il y en ait uneB;, affirme la rC)putC)e femme d'affaires quC)bC)coise DaniC(le Henkel, qui a dC; trimer dur pour percer l'univers masculin de l'entrepreneuriat avant d'en devenir une chef de file

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
This might be fixed in #1628 (@ngosset ?)

**Comment by ngosset** [comment]
> This might be fixed in #1628 (@ngosset ?)

Looks like it!
