### ISSUE TITLE
The link "National Cybercrime Coordination Unit (NC3)" has been changed

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1694]
## Summary

The link "National Cybercrime Coordination Unit (NC3)" has been changed from "http://www.rcmp-grc.gc.ca/en/the-national-cybercrime-coordination-unit-nc3" to "http://www.rcmp-grc.gc.ca/en/nc3" in English and  "http://www.rcmp-grc.gc.ca/fr/gnc3" in French

Please update 

## Steps to reproduce
- launch the application
- click on "Royal Canadian Mounted Police "  from the homepage (I think it should link to RCMP homepage http://www.rcmp-grc.gc.ca/en but it does not)
- click on "National Cybercrime Coordination Unit (NC3) " link from Privacy statement page
- click on "National Cybercrime Coordination Unit (NC3)" link from Terms and conditions page

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by lmcbhvu** [comment]
Ooops, I forget one more link
- click on "National Cybercrime Coordination Unit" in Your privacy page

**Comment by lmcbhvu** [comment]
![page](https://user-images.githubusercontent.com/60269104/77128416-6a1fec80-6a26-11ea-9526-3f2db8a84967.jpg)

**Comment by stephaniemgauthier** [comment]
Here are the new links: 

Eng - http://www.rcmp.gc.ca/nc3
Fre - http://www.rcmp.gc.ca/fr/gnc3

New media sends their apologies for forgetting to let us know!
