### ISSUE TITLE
Duplicate error message is displayed

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1695]
## Summary

Duplicate error message is displayed on Your Privacy and What do you think could be affected? pages. I think we should remove and display only one

## Steps to reproduce

![duplicatedError](https://user-images.githubusercontent.com/60269104/77070826-542c1080-69c1-11ea-97ff-7e1b3756405d.jpg)

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by amazingphilippe** [comment]
This is needed for accessibility purposes. the first is a list of all errors, the other is grouped with the input field.
