### ISSUE TITLE
Move up to the beginning of page when I check the mandatory box 

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1698]
## Suggestion / question

With a new design, if the user forget to check the mandatory box (Privacy statement or What do you think could be affected?), the error message will be displayed. When the user checks the box, it will bring up to the beginning of the page instead of staying at it is as the old design. The user has to move the page down in order to click on <continue> button. Should we keep the old design? The user just needs to click on the check box and then <Continue> button 

## Use case

> What would this address?

**Comment by amazingphilippe** [comment]
Since we are adding something on the page: above the form: we need to bring the attention to that new element. This is fixed by #1719
