### ISSUE TITLE
Store prodVersion (1.1.0 currently) and include in analyst email

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#1703]
## Summary

in `App.js` we display the prod version as well as the gitsha. We don't store or send that data anywhere. We should store the data in the report, then save it to the database (which will happen automagically if it's in the report object) and include it in the analyst email.

## Steps to reproduce

Submit a report. "1.1.0" doesn't appear anwhere in the database or analyst email.

**Comment by lchski** [comment]
Curious: why don’t we just use the commit hash for the currently-deployed version? Seems much more reliable than manually setting version and having to always increment the semver.

**Comment by lchski** [comment]
(To be clear: we can still semver, e.g. by [git tagging particular commits](https://git-scm.com/book/en/v2/Git-Basics-Tagging). But seems more useful to have the commit hash as a version, since it's much easier to plug it into GitHub and see what the code was like at that point.)

**Comment by sastels** [comment]
> Curious: why don’t we just use the commit hash for the currently-deployed version? Seems much more reliable than manually setting version and having to always increment the semver.

We're going to use both: an easy to understand semver that will increment as prod changes, and also keep track of the gitsha that's deployed.
