### ISSUE TITLE
If the user submitted the report in French, should the analyst report be in French as well?

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1705]
## Suggestion / question

If the user submitted the report in French, should the analyst report be in French as well? Currently, it is not completed in French

![report](https://user-images.githubusercontent.com/60269104/77128158-7a839780-6a25-11ea-986f-6f2774f93473.jpg)

## Use case

> What would this address?

**Comment by sastels** [comment]
We discussed this a while ago and I think we decide that it probably should be but that it's a lower priority than other issues around the new user flows and robustifying the backend. I'll add it as a "low priority" issue.

@anikbrazeau @amazingphilippe @emilykuret any thoughts?

**Comment by emilykuret** [comment]
Sounds good.

**Comment by anikbrazeau** [comment]
Good with this, the bilingual works :) 

Also related, have recently learned that in some cases having bilingual comms might actually increase trust and credibility in notifications from government!
