### ISSUE TITLE
Fail to submit the report if the user enters the start date or transaction date in the wrong format

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1707]
## Summary

Fail to submit the report if the user enters the start date or transaction date with one digit in day and/or month fields

## Steps to reproduce
- Launch the report
- Enter one digit in day or month field of start date
(Example: 1-02-2020 or 01-2-2020 or 1-2-2020)

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by lmcbhvu** [comment]
I know that our format for day and month is 2 digits. For long term solution, we should validate or reformat the date before submit. I think the best solution is to reformat the date. With this way, we don't care the user enters 1 or 2 digits

**Comment by sastels** [comment]
This should be fixed when we remove the WAF, right @davidheerema ?

**Comment by davidheerema** [comment]
Yup, once we remove the WAF a lot of issues will resolve.

**Comment by amazingphilippe** [comment]
In order to get better data to the analysts, can I suggest using a library like moment.js to ease the date validation? Issues like validating dates, which months contain a 31st day, preventing browsers from "correcting" invalid dates into valid ones (ex: 34/10/2018 turning into 3/11/2018), probably adding leading 0s to single digits, potentially even formating the date as "01 february 2020" for analysts to make their job easier....

Opinions?

**Comment by sastels** [comment]
IMO it depentds. If we want to do full validation (ie checking # days in the month, worrying about leap years, etc) then we should use a library. If we just want to do a rough validation (only digits allowed, month must be between 1 and 12, day 1 and 31, check it's in the past) then we can probably just write a few lines of validation code ourselves.

**Comment by amazingphilippe** [comment]
A comment I received from Steph (RCMP) the other day: Date fields are not synced to real calendar dates (i.e., Nov 31 does not exist). Lets figure out what is important here and then make a decision

**Comment by sastels** [comment]
this issue fixed by changing WAF settings. other date validation issues remain but are referenced in other issues.
