### ISSUE TITLE
Content not included in landmarks

### ISSUE THREAD

**Issue by JuliannaR** [cds-snc/report-a-cybercrime#171]
**Content not included in landmarks
 1.3.1 Info and Relationships**
HTML5 or WAI-ARIA landmarks are used on the page, but not all content is included.

When using HTML5 or WAI-ARIA landmarks it is best practice to include all content on the page in landmarks. In this way users of assistive technologies can use the landmarks for navigating the page without losing track of content.

Make sure that all content on the page is included in HTML5 or WAI-ARIA landmarks.

**How do I meet this criteria?**
Use one of the following techniques from WCAG 2:

ARIA11 Using ARIA landmarks to identify regions of a page
These references are taken from the Web Content Accessibility Guidelines 2.0.

<img width="1434" alt="screen shot 2019-03-06 at 5 56 19 pm" src="https://user-images.githubusercontent.com/35537308/53919879-4cf5c700-4039-11e9-9ee6-b4eca252b916.png">

**Comment by evadb** [comment]
I will take a look at this when I fix some content stuff!

**Comment by sastels** [comment]
This code has since been deleted. We should run a new accessibility assessment on the current prototype.
