### ISSUE TITLE
The error message " <!-- a padding to disable MSIE and Chrome friendly error page -->" should not be displayed

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1715]
## Summary

If the report is not successful to submitted, the user goes back to the previous page and the following message is displayed

![error](https://user-images.githubusercontent.com/60269104/77326640-776ffc00-6cf0-11ea-828c-c72d3072e4fa.jpg)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
We should probably allow the user to try to resubmit in this situation - thoughts?
