### ISSUE TITLE
No attachment is included in email or DB if the attachment is .txt file or .jfif file is included in the report

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1716]
## Summary

If the user includes the offensive file (such as bikini or gun pictures) in the report, this file will be not appeared in the analyst email and Database

## Steps to reproduce
- Launch the application
- Include the bikini or gun pictures in the report
Expected Result: this file should be included in DB and email
Actual Result: This file is not included in the DB and email

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
Was there a file section for the attachments in the report (in particular, was there a "Malware scan" line for that file?)

By default we are dropping files that either fail the malware scan or if the malware scan fails to run, so wondering if the issue is with the scanner rather than the email code.

**Comment by lmcbhvu** [comment]
It just says "No attached file  in the File attachments  section of analyst report and only have the file description information in database. I did send a report with virus file and the information about virus file (File name, size, CosmosDB, MalwareScan and image classification) is shown in File attachments.

**Comment by lmcbhvu** [comment]
Here is the updated
I  perform some tests on rcmp-dev and found that if the report will fail to submit if the user send attachment file in .txt or .jfif alone. If it is send with the other format (send 2 attachments one in png and one in txt), the report will go through but only one attachment in png see on the report and db)

**Comment by sastels** [comment]
It sounds from talking IRL that this is an issue with the WAF (@davidheerema ?) we should redo the test with the WAF turned off to verify.

**Comment by davidheerema** [comment]
@lmcbhvu @sastels Yes, this appears to only happen on environments front-ended by the WAF.  Testing can be done on CDS DEV environment (no WAF) or on any local environment to verify.

**Comment by lmcbhvu** [comment]
The report is submitted if the user send attachment file in .txt or .jfif alone but no attachment is included in the report if  .jfif file is attached
