### ISSUE TITLE
Language toggle clears data

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/report-a-cybercrime#1725]
## Suggestion / question

Mid form, clicking the language toggle clears the data. (On the page, in the whole state, I don't know...)

I believe we do this for reasons... right?

Therefore, should we warn users when they click on the language toggler?

## Use case

Losing data when toggling the language mid-form

**Comment by sastels** [comment]
essentially, we don't save the data until we click "continue", and when the language toggle is pressed the entire screen rerenders, restoring whatever default values there are for the form. Potentially we could use some sort of `onChange` handler to update values as they are typed. Not sure if it's worth the added complexity to the code though `¯\_(ツ)_/¯`

**Comment by justinr86** [comment]
This issue has been resolved in a previous update. I have confirmed this with @amazingphilippe, closing issue.
