### ISSUE TITLE
Add extra message in case the report cannot be submitted

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1743]
## Suggestion / question

As Stephanie's suggestion, it will be better if the user cannot submit their report, add an extra message like 
Thank you for reporting
Sorry, your report was not successfully submitted. Please call 1-888-495-8501 to report your incident

**Comment by anikbrazeau** [comment]
Consider trying to be unambiguous that submitting was not successful -- "Thank you for reporting" might give the impression at a glance that it worked

Recommendation:

**EN**

Sorry, something went wrong. 

Your report was not submitted. 
Please call 1-888-495-8501 to report your incident.

**FR**

Désolé, quelque chose a mal tourné.

Votre rapport n'a pas été soumis. 
Veuillez appeler le 1-888-495-8501 pour signaler votre incident.
