### ISSUE TITLE
 Should validate the file extension of attachment

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1750]
## Summary

We should add the validation on the file extension of attachment and notify the user if the file format is not accepted. Currently, the user can attach .jfif file in the report but this file will not be included in the email and DB

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
We do validate the extension, but it turns out that the `<input>` tag lets them through because .jfifs are really jpegs.

Closing this issue and replacing with #1753
