### ISSUE TITLE
Add testing around all validation

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#1758]
## Summary

We should have a bunch of tests around validation. anything bad fails, anything good passes.
- [x] email address
- [x] phone number
- [x] postal code

## Motivation

This will make it easier to ensure all cases are covered.

**Comment by lmcbhvu** [comment]
I run some tests on email address and found that it does not work with space ( ), dash (-), dot (.), &, +, !, % . The first three are very popular use. It works only with under score and no space such as lmcbhvu@gmail.com or Hong_vu@gmail.com
Phone and postal test are reported in the other issues

**Comment by sastels** [comment]
We can test the validation function directly, ie we don't have to submit the form to test validation (we can assume that final-form works). For example,
```
describe('validation', () => {
  afterEach(cleanup)

  it('passes correct phone numbers', () => {
    expect(validate({ phone: '1234567890' }).phone).toBeUndefined()
    expect(validate({ phone: '(123) 456-7890' }).phone).toBeUndefined()
    expect(validate({ phone: '123-456-7890' }).phone).toBeUndefined()
    expect(validate({ phone: '123.456.7890' }).phone).toBeUndefined()
    expect(validate({ phone: '(123)456-7890' }).phone).toBeUndefined()
  })

  it('fails incorrect phone numbers', () => {
    expect(validate({ phone: '123456789' }).phone).not.toBeUndefined()
    expect(validate({ phone: 'not a number' }).phone).not.toBeUndefined()
  })
})
```

**Comment by sastels** [comment]
testing added.
