### ISSUE TITLE
Should remove the Other option of What was affected page in database

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1762]
## Summary

In the current version, no Other option of What was affected page is displayed in the analyst email. It will be better if the Other option of What was affected page should be removed from the database as well

![form](https://user-images.githubusercontent.com/60269104/78073445-e98ab580-736e-11ea-910f-91810e6456f1.jpg)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
👍 this field is a leftover from when we had it.
