### ISSUE TITLE
The report cannot be submitted if it is anonymous report

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1772]
## Summary

> One paragraph explanation of the bug.

The  user will get the following error "Sorry, your report was not successfully submitted." id the user chooses to submit a report as anonymous report

> How exactly can the bug be reproduced? Be very specific.

- Launch report
- Choose anonymous to yes

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by lmcbhvu** [comment]
Steps to reproduce
Launch report
Choose anonymous to yes
Choose option Phone and once on how did it start
CHoose other on how does it affect
Enter some text at what happens
and skip the rest

**Comment by lmcbhvu** [comment]
Repeat the same steps but at location, enter city and province info

**Comment by sastels** [comment]
server crashes because it's expecting `contactInfo` in the data, but it's not there since that form got skipped.
```
(node:49319) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'email' of undefined
    at prepareUnencryptedReportEmail (/Users/sastels/Git/report-a-cybercrime/f2/src/utils/encryptedEmail.js:32:28)
```
