### ISSUE TITLE
Add more validation on date

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1786]
## Summary

More validation should be added on the date in moneylost page
1. If the user enters "0" on day, month or year (0-0-0000) --> No error is received.  It should give an error "Invalid date" or Start date/month/year must contain a real day/month/year"
2. If the user enters 30-02-2020 -> no error is received because no 30 on February. It should give an error "Invalid day or Date must contain a real day"
3. If the user enters 32-3-2020  or 2-13-2020-> the user will receive an error message "Start date must be in the past". It should be "Start date must contain a real day/month" or "Invalid day/month

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by davidheerema** [comment]
I just came here to report this as well
