### ISSUE TITLE
Location info should be consistent between anonymous report and non-anonymous report in analyst email

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1797]
## Summary

The location information (city and province) for non-anonymous report should be displayed the same way as non-anonymous report with no location info provided.

For non-anonymous report, the location (City and Province) is displayed under Victim Details section as "undefined"
For anonymous report, the location (City and Location) is still displayed under Victim Details section with real city and province 's name if the user entered or nothing if the user did not.

![location (1)](https://user-images.githubusercontent.com/60269104/78799730-88736b00-7988-11ea-8a29-3a029bc42ef9.jpg)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
fixed in #1794
