### ISSUE TITLE
New future feature: FYI flow

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#1811]
## Summary

**Lite version of the form:** Shorter flow to give the option of flagging something quickly, or something that they were not impacted by (eg non victims who are good samaritan reporters.)

## Design detail

Go from FYI landing page > privacy page > FYI what happened page > Attach Evidence > Location > Contact > Confim > Submitted

Frame 233 in Figma: https://www.figma.com/file/R054FzUOrpP13oTbMsQevj/Sprint-9?node-id=3281%3A476

(Privacy, Location, Contact, confirm and submitted pages are the same as current flow but Landing Page and what happened will be unique to this flow.)

## Unresolved questions
Changes logic/branching

**Comment by marthaedwards** [comment]
Content changes to this flow based on research have been implemented in both french and english
