### ISSUE TITLE
Analyst Reports not displaying special characters

### ISSUE THREAD

**Issue by stephaniemgauthier** [cds-snc/report-a-cybercrime#1824]
Special characters in the .html analyst report are not appearing properly.

body .txt = <tr><td>Name:          </td><td>A blackmailer in search of a "donation"</td></tr>
body .html = 
![SnipImage](https://user-images.githubusercontent.com/62033362/79366657-955d0500-7f1a-11ea-84bf-1ce0d8c7ec4e.JPG)

**Comment by sastels** [comment]
Curly quotes work fine when I send the unencrypted message to myself and view in Gmail. Is this Groupwise or Outlook? Can we test with the other one as well (@ngosset @kevinyang06 @davidheerema @DianeLiu2019 )?

**Comment by stephaniemgauthier** [comment]
The analyst are still using GW and the report html is opening is in IE.

**Comment by stephaniemgauthier** [comment]
After doing testing with Hong yesterday, it looks like the issue may need to bump in priority. French reports extremely difficult to work with.

**Comment by sastels** [comment]
One thing we could try is to convert unicode characters to ascii... we're already doing this to detect self harm words.
https://github.com/cds-snc/report-a-cybercrime/blob/master/f2/src/utils/selfHarmWordsScan.js#L12

**Comment by DianeLiu2019** [comment]
> Curly quotes work fine when I send the unencrypted message to myself and view in Gmail. Is this Groupwise or Outlook? Can we test with the other one as well (@ngosset @kevinyang06 @davidheerema @DianeLiu2019 )?

I did the same test as Steve's , send the unencrypted report to my cds email , it work fine for both single curly quote and double curly quote .
