### ISSUE TITLE
Make signalement.centreantifraude.ca load in FR

### ISSUE THREAD

**Issue by samburtonCDS** [cds-snc/report-a-cybercrime#1830]
## Summary

[signalement.centreantifraude.ca](signalement.centreantifraude.ca) currently loads the EN version of the site, but it should take users directly to the FR version.

**Comment by sastels** [comment]
This used to work, didn't it @ngosset ?

**Comment by sastels** [comment]
related: https://github.com/cds-snc/report-a-cybercrime/pull/1448

**Comment by ngosset** [comment]
Problem is the code is looking for the word "signalez" not "signalement" in the URL (window.location.hostname) . Would actually be a really quick fix.

**Comment by sastels** [comment]
👍 good catch Norm!
