### ISSUE TITLE
Confirm the FR CAFC site takes users to the FR version of NCFRS

### ISSUE THREAD

**Issue by samburtonCDS** [cds-snc/report-a-cybercrime#1831]
## Suggestion / question

If a user is navigating the CAFC site in FR and clicks on the report link, will the javascript code on the CAFC site redirect the user to the signalement. or the report. version of the service? 

In this case, it should take the user to signalement. , which should load in French. It's not clear if this is currently what's happening.

## Use case

Users navigating the CAFC site/reporting a cybercrime in French

**Comment by ngosset** [comment]
Hi @samburtonCDS . There was a bug here that was fixed with V1.2 release (Apr 28th)

PR #1852 
Issue #1830
