### ISSUE TITLE
Content Moderator Error when scanning pdf

### ISSUE THREAD

**Issue by davidheerema** [cds-snc/report-a-cybercrime#1833]
## Summary

 Error in Content Moderator: Error 

>There are Content Moderator Errors logged when someone is uploading a pdf.  It could be because we are passing this content to the Content Moderator and .pdf is not able to be scanned.  I see that one or two submissions had image files attached and they did not report this error.  I will open an issue in github to either have the Error elaborated (right now all it says is Error) or to do some testing to determine if pdfs should never be scanned, because they can't be, so that this error doesn't occur.

Is this actually an error if it is an expected case where we can't scan this?

## Steps to reproduce

> Attach a PDF and look at the console output for the server.js and see the error...

## Unresolved questions

> Elaborate on the "Error" and don't call it an "Error" to log it properly?

**Comment by lmcbhvu** [comment]
Currently, only the attachment .jpg, jpeg and .png are scanned

**Comment by davidheerema** [comment]
but it looks like pdf are still being sent to the scanner and there is an
error.

**Comment by lmcbhvu** [comment]
I got Malware scan: ERROR: Unable to perform virus scan for submission NCFRS-mgg9e08ma06 (staging) when it tried to scan PDF file. I uploaded 2 files to the report and because of that error, no file is attached in analyst email. It happened one time and I tried to reproduce it many times but I could not. I don't know is it related to what you report

**Comment by davidheerema** [comment]
No, Virus Scan is different than content moderator scan!  maybe the virus
scanning container is offline in staging environment?

**Comment by davidheerema** [comment]
Where do you see that error?  I checked and it appears that the container
is running...
