### ISSUE TITLE
Report version is missing in the analyst email 

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1836]
## Summary

Report version is missing in the analyst email 

## Steps to reproduce

1. Launch application
2. Choose anonymous report or not  (does not care)
3.  Skip How did it start page or choose once
4. Choose Other on How did it affect page
5. Enter Something on what happened page
6. Skip the rest and submit

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
I jiust noticed this today - I think it is there in the first report after you load the page, but not if you "create a new report" (or "cancel report". I think that we are setting the version number on app load but not restoring it when we clear all the report data .
