### ISSUE TITLE
The same fix on #1800 and #1808 should be applied on Transaction Date

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1842]
## Summary

The same fix on #1800 and #1808 should be applied on Transaction Date in "How were your money or finances affected?" page

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by DianeLiu2019** [comment]
fixed the issue in PR#1889
