### ISSUE TITLE
Duplicate information is displayed in the analyst email

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1844]
## Summary

The following information is displayed twice in the analyst email

Report Version
When did it start

Please see the below picture

![start](https://user-images.githubusercontent.com/60269104/79599591-befd6400-80b3-11ea-8954-c79b4488f7a9.jpg)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
contained in #1795
