### ISSUE TITLE
CAFC does not accept .png files

### ISSUE THREAD

**Issue by stephaniemgauthier** [cds-snc/report-a-cybercrime#1857]
Users are uploading .png files via the NCFRS. The CAFC rejects all of these file times.

The work around is for the Analyst to screen capture the .png image, save as a .pdf and upload to the CAFC.

.png files were not included in the original list of file types accepted by the CAFC so suggestion that these should be excluded from our app.

**Comment by stephaniemgauthier** [comment]
A change will also be needed to the text to strip out .png from the files accepted.

**Comment by davidheerema** [comment]
Man, CAFC really needs to modernize if they aren't accepting png...  we are forced to be crappy too because of that.

**Comment by DianeLiu2019** [comment]
the better way to deal with the issue is issue#1884
