### ISSUE TITLE
The phrase "WARNING: Image may be offensive" should be put on the harmful attachment 

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1864]
## Summary

The phrase "WARNING: Image may be offensive" should be put on the harmful attachment as well. Currently, only the sensitive image (girl in bikini) has that warning but not on the gun image

![gun](https://user-images.githubusercontent.com/60269104/80147889-30d92000-8582-11ea-93d5-56cb2f407dfa.jpg)
 

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
It doesn’t look like Content Moderator is flagging the gun image as racy or adult.

We could look into broadening the definition of what is considered harmful and investigate what type of automated scanning is available for that.

**Comment by lmcbhvu** [comment]
This issue will be closed because it is duplicate with issue #1910 and it is fixed in #1914

**Comment by lmcbhvu** [comment]
This defect is fixed
