### ISSUE TITLE
Failed to submit the report if the user skip the location and contact detail pages

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1867]
## Summary

Failed to submit the report if the user skip the location and contact detail pages

## Steps to reproduce

- Choose to non-anonymous report
- Press Skip button at location and contact detail pages

![failed](https://user-images.githubusercontent.com/60269104/80245386-9b4c9780-8638-11ea-99d5-9d974b034ae1.jpg)

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
Fixed by #1863
