### ISSUE TITLE
Failed to submit a report if the user removes an information that is entered before 

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1872]
## Summary

Failed to submit a report if the user update some changes in the business page 

## Steps to reproduce
- Choose "Business" at what could be affected page
- Fill out name, type of business, role and size of business
- You can press continue or skip for the remaining pages
- At summary page, edit the business and remove value from role or type of business
- Press submit

![failed](https://user-images.githubusercontent.com/60269104/80406441-13fa6080-8892-11ea-91a8-16dffc9a838a.jpg)

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by lmcbhvu** [comment]
I do test with different scenarios and I found it happened everywhere if the user want to remove the information in any field that he/she entered before.  The above case is just one of cases.
For example: 
At money lost, first you enter Money asked and money lost. At summary page, you remove the money lost.
At device affected page, you enter type of device and type of account and the remove the date in one of them at summary page
....

**Comment by lmcbhvu** [comment]
It can happen the user enters the information and then change their mind to remove it immediately

**Comment by khalidelaggan** [comment]
@kevinyang06 are you working on this? Let me know if you want to pair and needs another pair of eyes? I'm available until 12.
