### ISSUE TITLE
The user get stuck at contact info page if the user wants remove to phone or email address

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1873]
## Summary

After choose to submit the non-anonymous report with entering name, gmail and phone. AT summary page, the user wants to edit contact info and remove email or phone. After the user remove the phone number,  the error message "enter a phone number that contains 10 digits" keep display when the user press continue button. Similarly  it happened with email address. 

## Steps to reproduce

- Choose  to submit non-anonymous report
- Enter name, email and phone at contact detail info page
- At summary, edit that section and try to remove phone or email and press continue

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by lmcbhvu** [comment]
It happened with location page too. If the user wants to edit the location at summary page and remove the location information

**Comment by stephaniemgauthier** [comment]
Also, need more validation on the email address as I was allowed to enter this:
red@sfdsf

**Comment by sastels** [comment]
Possibly our form validation doesn’t allow empty fields?

**Comment by lmcbhvu** [comment]
The user also got stuck If the phone or email is entered and then removed immediately.

**Comment by amazingphilippe** [comment]
The validation does not allow for empty values. #1902 should make this clearer.
