### ISSUE TITLE
Error on Analyst Report

### ISSUE THREAD

**Issue by stephaniemgauthier** [cds-snc/report-a-cybercrime#1879]
A report was received 2020-04-27 at 22:18 that included an error. Only the Report Information was present. 
html: 
![Report errot html](https://user-images.githubusercontent.com/62033362/80510778-3307f980-8949-11ea-86f7-f3c9a085cb1b.JPG)
txt: 
![report error txt](https://user-images.githubusercontent.com/62033362/80510792-39967100-8949-11ea-902a-b90b8acedb2e.JPG)

No other information on the report came through except 2 files uploaded and attached fine to the report.

**Comment by sastels** [comment]
This is due to the email formatter not having a value for `personalInformation` - this *should* be fixed in the latest master / staging / prod with possible exceptions related to #1872
