### ISSUE TITLE
Don't pass non-images to Content Moderator for scanning

### ISSUE THREAD

**Issue by davidheerema** [cds-snc/report-a-cybercrime#1885]
## Summary

The server logs an ERROR when we pass .rtf or .pdf attachments to the content moderator for scanning.  That service is only able to scan bmp, png, jpeg, and gif.

See https://canadacentral.dev.cognitive.microsoft.com/docs/services/57cf753a3f9b070c105bd2c1/operations/57cf753a3f9b070868a1f66c/console

This should not be an error and it makes alarms trigger.

## Steps to reproduce

> Upload a supported file type other than those four and check the console log for the error.

## Possible Solution:

If the attachment is not bmp, png, jpeg, or gif content type (who cares about the file extension) then do not scan the that file.

**Comment by davidheerema** [comment]
@DianeLiu2019 John seems to have taken care of this Issue in his PR 1890.  Take a look if you wish to see how he did it.

**Comment by DianeLiu2019** [comment]
Yes, he fixed. so I close this issue now.

**Comment by DianeLiu2019** [comment]
Yes, I saw it, It is good experience to learn how to fix this kind issue. I leave it here to automatically close.

**Comment by DianeLiu2019** [comment]
fixed in PR#1890

**Comment by DianeLiu2019** [comment]
Yes, John fixed the issue in RP 1890. It's good experience to work on this kind of issue. I close it now
