### ISSUE TITLE
Server encountered Error when sending confirmation Email?

### ISSUE THREAD

**Issue by davidheerema** [cds-snc/report-a-cybercrime#1886]
## Summary

> See the attached Server log.  but it looks like an uncaught error during email validation.  Maybe this is an error when we try to send out the confirmation email and they didn't include a valid one...

## Steps to reproduce

> I am not sure, testing needs to be done to reproduce @lmcbhvu 

<img width="1163" alt="Uncaught1" src="https://user-images.githubusercontent.com/51758091/80611656-e552c600-8a08-11ea-864b-287d19b4100f.png">

**Comment by lmcbhvu** [comment]
This issue can be closed because I could not reproduce in our current version. It happened in the previous version
