### ISSUE TITLE
React state warning

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/report-a-cybercrime#1894]
## Summary

One warning is popping up on Location Info Form and Confirmation Page.

Looks a bit like this:
> Warning: Cannot update a component (`StateProvider`) while rendering a different component (`ConfirmationSummary`). To locate the bad setState() call inside `ConfirmationSummary`, follow the stack trace as described in https://fb.me/setstate-in-render

We are doing some funky stuff in those two pages:

Confirmation summary: 
```js
  if (!data.doneForms) {
    dispatch({ type: 'saveDoneForms', data: true })
  }
// Sets doneForms to true if the user successfully render this page. This is how we let users edit info
```
Location Info Form:
```js
  const [data, dispatch] = useStateValue()

  let location
  if (!data.formData.location) {
    dispatch({ type: 'saveFormData', data: { location: defaultLocation } })
    location = defaultLocation
  } else {
    location = {
      ...defaultLocation,
      ...data.formData.location,
    }
  }

// fixed by doing like on all the other forms:
const [data] = useStateValue()

  const location = {
    ...defaultLocation,
    ...data.formData.location,
  }

```

## Steps to reproduce

1. `npm run dev`
1. Open dev console
2. Navigate to Location or Confirmation pages

## Unresolved questions

Figuring out what we meant to do with these code snippets

**Comment by sdzhangtao** [comment]
This is a limitation from React, you can set state in the render, but not other components state. Use hooks can resolve this issue. useEffect
