### ISSUE TITLE
Update privacy statement for analytics

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/report-a-cybercrime#1926]
## Summary

Since we are now tracking information about the reports, we have to update the privacy statement in both languages. 

## Design detail

[This document](https://docs.google.com/document/d/1c0ov9OEwQI-p3SJxCkoiVc5My4Qe10AP63LJAPDIcck/edit?ts=5ebed7fb) Contains both languages of the privacy statement. We need to add the "Web Analytics" section in English and the "Analytique Web" en français. 

Also, we need to remove the old analytic sections: 
- "Autorisation de collecter vos renseignements personnels" and
- "Authorization to collect your information"

## Checklist
- [ ] "Web analytics" replaces "Authorization to collect your information"
- [ ]  "Analytique Web" replaces "Autorisation de collecter vos renseignements personnels"

**Comment by samburtonCDS** [comment]
Thanks so much for moving this forward @amazingphilippe ! I noted this in @DianeLiu2019 's pull request, but adding it here as well for visibility -- the "authorization to collect your information" section should remain in the privacy statement. That section wasn't in the Google Doc for some reason (I added it just now), but the new Web Analytics section doesn't replace it. Apologies for the confusion!
