### ISSUE TITLE
Should the privacy consent page be recorded as the other page?

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1929]
## Summary

When you click consent on privacy page, go to the next page and then click on go back button.  This check on privacy consent is not saved like the info on the other pages are saved.
Should the privacy consent page be recorded?

## Steps to reproduce

1. Click check box on privacy page
2. Process to a few pages and then go back to the previous pages

Actual result: The check box  on consent page is unchecked but the info which is entered on the other pages still exist when you go back to to previous pages 

## Unresolved questions

**Steve on Slack**
That’s odd. Two possibilities I can think of
1. We’re explicitly clearing it when we go to that page
2. We don’t use the saved value when we create the form (Ie we just use the default value when you create the form, which is not checked)

**Comment by DianeLiu2019** [comment]
@sastels  @anikbrazeau ,did we discuss the issue before. I have the impression we leave the check on privacy consent unsaved on purpose. is it?
