### ISSUE TITLE
Go Back phantom button

### ISSUE THREAD

**Issue by justinr86** [cds-snc/report-a-cybercrime#1943]
## Summary

The 'Go Back' button (link) fills the entire parent's width. This is confusing as clicking in the middle of the page will go back one step.

## Steps to reproduce

Begin filling out a report, then click to the right of the link. This will navigate to the previous page.

![GoBack](https://user-images.githubusercontent.com/62246403/82825859-fa8d0a00-9e79-11ea-89af-17c86b83c744.png)

**Comment by justinr86** [comment]
This also affects radio buttons and checkboxes. CSS property **width="fit-content"** should be applied to resolve issue.

**Comment by ngosset** [comment]
@amazingphilippe @khalidelaggan  Thoughts? From a design/accessibility point of view?

**Comment by amazingphilippe** [comment]
It's definitely a nice thing to fix. You would only expect to click on the content and not outside
