### ISSUE TITLE
Provide the city/municipality and prov/terr on the Analyst Report when given the postal code

### ISSUE THREAD

**Issue by stephaniemgauthier** [cds-snc/report-a-cybercrime#1950]
The Analysts need to identify the city/prov on the reports so they know which POJ to refer the file to. It's also needed to have this information for trend analysis.

If the report includes the postal code, the Analyst Report should pull from a Canada Post lookup table to auto-populate the City/Municipality and Prov/Terr.

**Comment by ngosset** [comment]
RCMP has a copy of the Canada Post postal code db and is used on many apps for this very purpose. If we need a copy for this issue I can look into it.
