### ISSUE TITLE
 French privacy statement: Some text should not be on the links

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1959]
## Summary

 When I compare the privacy statement in the report and in the document, some text should not be on the links. Please see the attached file for more info

![difference](https://user-images.githubusercontent.com/60269104/83163460-0e827700-a0d9-11ea-974b-008f9bd694a1.jpg)
![difference1](https://user-images.githubusercontent.com/60269104/83163477-13dfc180-a0d9-11ea-8097-ab00901ca7a0.jpg)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by amazingphilippe** [comment]
Comparing with English text, what is currently in the French code makes more sense than what is in the document. Should we still fix this? @anikbrazeau @lmcbhvu

**Comment by anikbrazeau** [comment]
I think this gets resolved by #1942

**Comment by lmcbhvu** [comment]
If we decide to keep the code, please update the document and this issue can be closed @anikbrazeau ,  @amazingphilippe

**Comment by DianeLiu2019** [comment]
> Comparing with English text, what is currently in the French code makes more sense than what is in the document. Should we still fix this? @anikbrazeau @lmcbhvu

@amazingphilippe Could you please check if I add wrong text on the links?
