### ISSUE TITLE
Should remove  web address "report-dev.con.rcmp-grc.gc.ca says" in the warning message

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1980]
## Summary

We should remove  web address "report-dev.con.rcmp-grc.gc.ca says" in the warning message when the user loads 0 bytes or >4MB file

![warning](https://user-images.githubusercontent.com/60269104/83668958-cfec3100-a59e-11ea-80f0-27dd821aea8f.jpg)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by ngosset** [comment]
Let's try with different browser & re-assess next prioritization session

**Comment by lmcbhvu** [comment]
@Norm, you are correct. I tried with different browsers and each of them has different formats. Please see the attached file. I think I will close this defect.

![browser](https://user-images.githubusercontent.com/60269104/84073809-7d948100-a99f-11ea-8976-af5263ebba13.jpg)
