### ISSUE TITLE
Add a link to the Thank You page

### ISSUE THREAD

**Issue by stephaniemgauthier** [cds-snc/report-a-cybercrime#2039]
Can we add the following link to the thank you page as the 1st in the list under "Where you can find help:"
ENG: https://www.rcmp-grc.gc.ca/en/cyber-safety/staying-cyber-healthy
FRE: https://www.rcmp-grc.gc.ca/fr/cybersecurite/assurer-sa-securite-ligne

**Comment by DianeLiu2019** [comment]
communicate with Stephanie, the text is 
ENG: Staying cyber healthy
FRE: Assurer sa sécurité en ligne
