### ISSUE TITLE
[react-ga] gaTrackingID is required in initialize()

### ISSUE THREAD

**Issue by sleepycat** [cds-snc/report-a-cybercrime#204]
It appears that the Google Analytics ID is not being passed into the app.

**Comment by sastels** [comment]
That's odd. Was it ever? I can't seem to find in in our Google Analytics account...

**Comment by sastels** [comment]
huh, looks we don't have secrets for the frontend code.

**Comment by sastels** [comment]
after talking IRL it looks like the problem is that the ID isn't in the cloud build container when the frontend's docker image is built.

**Comment by sastels** [comment]
@sleepycat fixed this in #350 🎉
