### ISSUE TITLE
Scroll bars on landing page

### ISSUE THREAD

**Issue by sleepycat** [cds-snc/report-a-cybercrime#205]
The landing page is longer than the browser window resulting in scroll bars.
The culprit is `min-height: calc(100vh - 55px);` in src/App.js, but finding an approach to sticky footers that doesn't require fixed pixel heights might be worth exploring.
![offscreen](https://user-images.githubusercontent.com/109692/54853798-3ac98900-4cc7-11e9-8c01-f4f36eed1242.png)

**Comment by sastels** [comment]
even more disturbing: no bar on Firefox, has the bar on both Safari and Chrome.

**Comment by evadb** [comment]
seems fun - I'm going to work on this

**Comment by evadb** [comment]
it fixed
