### ISSUE TITLE
Should find a way to update the version everytime to move code from dev to staging

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2058]
## Summary

We should find a way to update to the new version everytime to move a code from dev to staging to avoid to create an issue because of wrong version

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by ngosset** [comment]
Right now the version is hard coded and we include the commit hash. 

I don't see another solution other than putting the version # in an environment variable, but this isn't any better as with an environment variable you can't ensure the code was actually updated.

Closing for now.
