### ISSUE TITLE
What is the expectation if the user wants to go back to previous page after they click on "Return to the previous version." link?

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2059]
## Summary

What is the expectation if the user want to go back to previous page after they click on "Return to the previous version." link? The old and new way are totally different behaviors

Old implementation: 
If the user clicks on "Return to the previous version." in the main or any page of report, it will open a new page and direct them to go to https://www.antifraudcentre-centreantifraude.ca/report-signalez-eng.htm website. The user can still be able to come back and forth between the CAFC and NCFRS website if they change their mind and want to continue to fill out the report in NCFRS website

New implementation:
If the user clicks on "Return to the previous version." in the main of report, it will use the same page and direct them to go to https://www.services.rcmp-grc.gc.ca/chooser-eng.html.  If the user wants to go back to the NCFRS website using the back arrow key, the empty page of NCFRS will be displayed and the user has to refresh the page to get start page of NCFRS report. Only on Google Chrome and Internet explorer, the user has to do the extra step (refresh the page) to get back to the starting page. 

If the user clicks on "Return to the previous version." in the any page of report (after consent page), it will use the same page and load the website https://www.services.rcmp-grc.gc.ca/chooser-eng.html.  If the user wants to go back to the NCFRS website using the back arrow key, it will take the user to consent page of the report

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by DianeLiu2019** [comment]
after discussing with @stephaniemgauthier,  we change to open a new browser after click "  Return to the previous version." That way they may choose to go back to the NCFRS in the other window and use the feedback survey to send us some comments about why they clicked "return to previous version" or finish up on their report.
