### ISSUE TITLE
Mobile styling issues

### ISSUE THREAD

**Issue by evadb** [cds-snc/report-a-cybercrime#206]
![Screen Shot 2019-03-25 at 5 51 16 PM](https://user-images.githubusercontent.com/1545806/54956580-af4e3300-4f26-11e9-9ccb-5ac36af6115b.png)

Noticing some issues in the mobile styling of pages, especially on pages with forms

**Comment by sastels** [comment]
I think the width prop in the `Container`s is doing something wonky.

**Comment by sastels** [comment]
fixed now

**Comment by evadb** [comment]
email blast from the past

**Comment by sastels** [comment]
word.
