### ISSUE TITLE
The links in thank you email should be updated as well

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2071]
## Summary

The links in thank you email which is sent to the reporter should be updated as well to make it consistent with thank you page. Below is the update needed

1. Add a new link "Staying cyber healthy."
2. Update link "Stay up-to-date on what scams are most common." 

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by kevinyang06** [comment]
there is no code change, the change is on notify
