### ISSUE TITLE
Some harmful words in English have not been detected 

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2077]
## Summary

Some harmful words in English have not been detected and they are

Kill -> killer
Suicide ->  suicides, suicided, suiciding
Overdose -> overdoses, overdosed, overdosing
Hurt -> hurts,hurting
Destroy -> destroys, destroyed, destroying
It's over -> it is over
Pills -> pill
Knife -> knives

**Comment by justinr86** [comment]
> ## Summary
> Some harmful words in English have not been detected and they are
> 
> Kill -> killer
> Suicide -> suicides, suicided, suiciding
> Overdose -> overdoses, overdosed, overdosing
> Hurt -> hurts,hurting
> Destroy -> destroys, destroyed, destroying
> It's over -> it is over
> Pills -> pill
> Knife -> knives

The self harm key word scan uses a porter stemmer in an attempt to find the root word. This algorithm does have limitations. Use this website to preview what the stemmer will produce: http://9ol.es/porter_js_demo.html

I have included the stemmed words in parenthesis below:

Kill -> killer (killer)
Suicide -> suicides, suicided, suiciding (suicid, suicid, suicid)
Overdose -> overdoses, overdosed, overdosing (overdos overdos overdos )
Hurt -> hurts,hurting (hurt hurt)
Destroy -> destroys, destroyed, destroying (destroi destroi destroi )
It's over -> it is over (it is over )
Pills -> pill (pill)
Knife -> knives (knive)

None of these stemmed words match a self harm key word. The words to match are:
'Suicide, Suicidal, Kill, Murder, End Life, Pills, Hurt Myself, Overdose, Giving Up, Destroy, Gun, No Hope, Better Off, It's Over, its over, Knife, Depressed, Suicidaire, Tuer, Fin de la vie, Pilules, Médicaments, Se faire mal, Se blesser, Surdose, Abandonner,  Abandon, Détruire, Fusil, Plus d'espoir, plus despoir, Pas d'espoir, pas despoir, Sera mieux, Serai mieux, C'est fini, cest fini, Couteau, Déprimé, Dépression'

Only a result that matches one of these strings will be flagged as a self harm key word.

**Comment by sdzhangtao** [comment]
We can define the self harm words using stemmed words. That's typical when we do the soundex matching

**Comment by ngosset** [comment]
I think I'm going to go ahead and close this one. I believe the final NCS solution will likely do this kind of scanning for us, in the interim we can do status quo and use the legacy system's word list.
