### ISSUE TITLE
French harmful word will not be detected if they are conjugated

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2078]
## Summary

French harmful word will not be detected if they are conjugated. For example
Se faire mal -> Je me fais mal
Tuer -> je tue
Se blesser -> Je me blesse or je me suis blessé
Abandonner -> j'abandonne
Détruire -> Je détruis

**Comment by justinr86** [comment]
> ## Summary
> French harmful word will not be detected if they are conjugated. For example
> Se faire mal -> Je me fais mal
> Tuer -> je tue
> Se blesser -> Je me blesse or je me suis blessé
> Abandonner -> j'abandonne
> Détruire -> Je détruis


I don't speak French but below are the results after tokenize and stem. 

Se faire mal -> Je me fais mal (je fai mal )
Tuer -> je tue (je tue )
Se blesser -> Je me blesse or je me suis blessé (je bless je sui bless )
Abandonner -> j'abandonne (abandonn)
Détruire -> Je détruis (je detrui)

**Comment by ngosset** [comment]
I'm going to close this one for now ahead of the Azure Migration. In our end state, the internal solution will use NLP to improve these checks for us. In the interim I think matching the legacy system's word list is fine.
