### ISSUE TITLE
Selected types should be translated in French as well

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2082]
## Summary

If the report is in french, the selected types should be translated to french as well
For example:
No -> Non
French -> Français
None -> Aucun
Clean -> Propre
Credit card -> Carte de crédit
Gift card -> Carte-cadeau
Other -> Autre
etc .....

## Steps to reproduce
1. Submit a report in french

![french](https://user-images.githubusercontent.com/60269104/86960204-2e23ab00-c12d-11ea-812e-f8129001efdf.jpg)

**Comment by dengcn** [comment]
Issue had been reproduced at local dev environment

**Comment by dengcn** [comment]
I made code changes to address the needs to generate FRENCH type value for the word below:
No -> Non
French -> Français
None -> Aucun
Clean -> Propre
Credit card -> Carte de crédit
Gift card -> Carte-cadeau
Other -> Autre

Since such values are very limited and countable. Before we decide to go database approach, code changes can address such needs.  

Could you "lmcbhvu" think what else you found and may find similar to this, so that I can implement them in this fix. Thanks!.

**Comment by dengcn** [comment]
Hong, I fixed most of mentioned French in my dev.  One question for you what was the problem and under what scenario you mentioned "Clean" also needs to be properly presented with French? Thank

**Comment by dengcn** [comment]
Hong and team

There are following displays in both English and French which fall into this case, Here is what I proposed to present in English and French, feel free to correct me or advise which is more appropriate. 

Current Display:     Proposed English, Proposed French
-----------------------------------------------------------------------------------------
financial:                        “Finance”    “La finance”
personalInformation:  “Personal Information”  “Renseignements Personnels”
devices:   “Devices”  “Dispositifs”
business_assets   “Business Assets”  “Actifs Commerciaux”
other   “Others”  “Autres”
---------------------------------------------------------------------------------------

**Comment by dengcn** [comment]
Hong:

I already figured out which will trigger "Clean" as you listed.   I will use "Nettoyer" for French under such scenario when "Clean" happened in file upload/scan shown in French submission if there is no objection.

**Comment by lmcbhvu** [comment]
Here is the list 
French  -->  Français
Yes    -->  Oui
None --> Aucun
No --> Non
Email --> Courriel
Phone --> téléphone
Once --> Une fois
Several times --> Plusieurs fois
Not sure--> Pas certain
Online -> En ligne
App --> App
Others --> Autres
Financial --> Finances
personal information -->  Données  personnelles
devices --> appareils
business_assets --> Entreprise
Other --> Autre
Credit card --> Carte de crédit
Dob --> DDN
Home address --> Adresse du domicile
Sin -> NAS
More -> Pus
To -->  à
E transfer --> Transfert électronique
Gift card --> Card-cadeau
Cryptocurrency --> Cryptomonnaie
Clean --> Propre
True --> Vrai
Warning: Image may be offensive  à Alerte : L'image peut être choquante
Fields missing from above report  à Champs manquants dans le rapport ci-dessus

**Comment by dengcn** [comment]
Hong, Thank you very much for more scenario and its French wording.

**Comment by lmcbhvu** [comment]
Ooops, I forgot a new page is added and need to be translate as well
Myself --> Moi-même
Someone I know  --> Une connaissance
A business --> Une entreprise

**Comment by lmcbhvu** [comment]
I asked my friend who is very good in French and here is her advice for the following words
Warning: Image may be offensive -->  Avertissement : L’image peut être offensante
Fields missing from above report  --> Champs manquants dans le rapport ci-dessus

**Comment by dengcn** [comment]
Hong. 

For the following 3 on your list, under what business flow will these 3 fall into final analyst report? I completed others on your added list, did not reproduce these 3, thanks.
 
More -> Pus
To --> à
True --> Vrai

**Comment by lmcbhvu** [comment]
I made a mistake
More -> Plus (missing "L")
