### ISSUE TITLE
Bug : Analyst Report Suspect Header Error

### ISSUE THREAD

**Issue by Cassista** [cds-snc/report-a-cybercrime#2125]
Since the release of version 1.6, analyst reports have incorrect suspect headers.

The old version of analyst reports indicated " They asked (information): " and " I lost (information): ", the new reports now indicate " Information obtained by the suspect " and " Information obtained by the suspect ". 
According to the questions asked on the current website, the new analyst reports should indicate "Information requested by the suspect" and "Information obtained by the suspect". 

**OLD VERSION**

![Old version](https://user-images.githubusercontent.com/68609954/88174750-d12af900-cbf2-11ea-8ab4-97404ea825ba.PNG)

**NEW VERSION**

![New version](https://user-images.githubusercontent.com/68609954/88099009-9b413280-cb68-11ea-9f75-320a864082ea.PNG)

**CURRENT WEBSITE** 

![Current website](https://user-images.githubusercontent.com/68609954/88099021-9ed4b980-cb68-11ea-8387-b1ae6964641c.PNG)

**Comment by justinr86** [comment]
Looks like the message property **confirmationPage.personalInformation.typeOfInfoObtained** is being used twice in **formatAnalystEmail.js**.

Need to change first message prop to **confirmationPage.personalInformation.typeOfInfoReq**.
