### ISSUE TITLE
Remove Missing Fields From Analyst Email

### ISSUE THREAD

**Issue by justinr86** [cds-snc/report-a-cybercrime#2128]
We currently dump JSON at the end of the analyst email if fields are omitted from the submission. This will occur more frequently in the future as we edit and create new forms. For example, the FYI Flow skips many pages. It doesn't make sense to insert (blank) information the user didn't enter - especially if they were never asked. 

This seems like it was used to test the submission/email function and is still part of the code. This is not meaningful information to an analyst and the format will make it confusing to some who is not technical.

The app should be able to handle not having some fields entered or displayed at all. There are a few ways to resolve this:

1. Simply remove this portion of the email

1. Format this section to make easier to read

1. Change this section of the email to a log message/email to a dev account

This will require more discussion to determine the best solution.

![missingFields](https://user-images.githubusercontent.com/62246403/88285546-4bc04b00-ccbd-11ea-82ac-90cff0127966.png)

**Comment by stephaniemgauthier** [comment]
Decision to leave the missing fields at the bottom to remind developers that the report template needs to be updated.
This issue should be to update the report template according to the new fields.

**Comment by ngosset** [comment]
We need to keep this feature as it's a "catch all" so that the report values are passed onto the analysts even when a dev forgets to add new fields to the report template, but we could probably clean it up or not send it when the "value" part of the json key-value pair is empty.

**Comment by ying-chen-cds** [comment]
You need to delete the fields if they are already added in the report
