### ISSUE TITLE
finalFeedbackThanks page content change

### ISSUE THREAD

**Issue by DianeLiu2019** [cds-snc/report-a-cybercrime#2131]
## Summary

we have different content in post feedback page  between current version and Figma.   Currently,  the content is different in finalFeedbackThanks page depend on if the report has been submitted successfully.  Pointed the different to designer @marthaedwards , she suggested use the  figma versionfor all feedback submissions.

## Steps to reproduce
currently, report submitted successful, then  finish feedback, then finalFeedbackThanks page is that

![image](https://user-images.githubusercontent.com/51336707/88407239-d5484980-cd9f-11ea-8bbc-2ff54996372c.png)

report submitted unsuccessful, then finish feedback, then page is that

![image](https://user-images.githubusercontent.com/51336707/88407681-76370480-cda0-11ea-938f-e18cabb15ef9.png)

in figma, the finalFeedbackThanks page is that

>
![image](https://user-images.githubusercontent.com/51336707/88407850-b5fdec00-cda0-11ea-83c8-5152dba41a63.png)

 
## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by stephaniemgauthier** [comment]
So the user will get the final page above after clicking Tell Us More on the Confirm Cancel page:
![Figma Frame 231 Cancel Report](https://user-images.githubusercontent.com/62033362/88582411-adb1e500-d01c-11ea-9543-90f6a256f55f.jpg)
