### ISSUE TITLE
remove " Fields missing from above report"  part in analyst email after sending attached file in evidence page by using "start report" version

### ISSUE THREAD

**Issue by DianeLiu2019** [cds-snc/report-a-cybercrime#2170]
> One paragraph explanation of the bug.
we should remove this part: 
Fields missing from above report  { "_id": "xxxxxxxxxxxx" } from analyst email after sending attached file(only .png or .jpg file type have this problem)  in evidence page 

## Steps to reproduce
in landing page, choose " start report" , follow the report flow. In evidence page, we attach a .png or .jpg file(only those two types file have the problem) ,  then finish the report. In analyst email ,we will receive : Fields missing from above report
{ "_id": "xxxxxxxx" } at the bottom of the analyst email 
 
![image](https://user-images.githubusercontent.com/51336707/89445736-8dbba900-d721-11ea-9eb7-e9734f50db94.png)
> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by DianeLiu2019** [comment]
The issue is not exit anymore

**Comment by ngosset** [comment]
I'd like to keep this feature incase we forget to add a field to the template, but we can add code to hide/exempt fields that are "under the hood" and not important to the analyst
