### ISSUE TITLE
Should we make 'Who do you report for' page mandatory to select at least one option?

### ISSUE THREAD

**Issue by kevinyang06** [cds-snc/report-a-cybercrime#2171]
## Suggestion / question

> The purpose of this page is to record the information about who does the user report for(my-self, someone-else or a business) , but now it can be skipped without any input.

## Use case

> What would this address?

**Comment by ying-chen-cds** [comment]
The code implementation is following the design in the Figma. I think the design is that if no option is chosen, it's not a 3rd party reporting. Same for "When did it happen" page, it's not necessary to choose an option.

**Comment by ngosset** [comment]
Add validation, don't set a default.

**Comment by DianeLiu2019** [comment]
the issue will be fix by updating the form using formik
