### ISSUE TITLE
The Attach supporting evidence page in the Submit a tip flow should be consistent with the Full report flow

### ISSUE THREAD

**Issue by stephaniemgauthier** [cds-snc/report-a-cybercrime#2186]
**Submit a tip:**

![image](https://user-images.githubusercontent.com/62033362/89916766-027d6000-dbc6-11ea-9b97-ba444a0c482a.png)

**Full Report:**

![image](https://user-images.githubusercontent.com/62033362/89916940-32c4fe80-dbc6-11ea-83b9-4fa72c6607c1.png)

**Comment by dengcn** [comment]
Hello Stephanie. I am working on PR2186.   Just wish to clarify, as for the allowed file display on File Attachment and these on final report, both will follow how they are displayed on final report?

**Comment by lmcbhvu** [comment]
The PR#2180 is fixed the issue in red circle but one more description "**Images of receipts, transactions, or packing slips.**" should be added to FYI flow. It should be:


If you can, include things such as:

Screenshots of webpages, conversations, or email threads.
Images of receipts, transactions, or packing slips.
Documents that show the demands made by the suspect.

**Comment by dengcn** [comment]
I see, just tested and saw these missing in FYI flow

**Comment by dengcn** [comment]
In full report evidence page, we have **"It’s okay if you didn’t keep any documentation from the incident. You can skip to the next section."**

Do we also need this section in Short Report? Currently this paragraph is not shown in short report
