### ISSUE TITLE
Phone number in contact info page should be validated

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2189]
## Summary

Phone number in contact info page should be validated. Currently, it accepts the letters and less than 10 characters (full and fyi reports)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by justinr86** [comment]
It was decided the validation should be removed for the time being to allow for international phone numbers.

**Comment by lmcbhvu** [comment]
Do you think it should be at least validated to accept the digit numbers only and remove phrase (Enter a phone number that contains 10 digits.) because the international phone number is more than 10 digits

**Comment by ying-chen-cds** [comment]
I'll remove the phrase (Enter a phone number that contains 10 digits.) and add a loose validation (only allow numbers, space, brackets and hyphen)

**Comment by justinr86** [comment]
Looks like we have a duplicate issue #2194.

**Comment by ying-chen-cds** [comment]
I had a look, it is related, but not duplicate.

**Comment by ngosset** [comment]
Coming out of the prioritization meeting it sounds like we do want validation but we need to handle cases such as international numbers and phone extensions. It may be worth looking for an existing react component for phone input

**Comment by dengcn** [comment]
Hello: @ngosset and @stephaniemgauthier  @lmcbhvu  

I have prototype ready and following formats(not limited to) will be validated and pass.

I did research, for all GOOD international number, it must be more than or equal to (>= ) 7 digits, then use regex algorism, following GOOD number will pass validation

console.log(isValidPhonenumber('00116131122323')) //=> true
console.log(isValidPhonenumber('001863454516131122323')) //=> true
console.log(isValidPhonenumber('++1-7134445+345')) //=> true
console.log(isValidPhonenumber('1.713.444.5345')) //=> true
console.log(isValidPhonenumber('+09-323-333-3332')) //=> true
console.log(isValidPhonenumber('853-12349543')) //=> true
console.log(isValidPhonenumber('8534444')) //=> true

Could you please check if above examples sufficient to cover good one, or what else format you thing we should get phone number validation pass? Thx
