### ISSUE TITLE
Staging: Image Moderator Identified .jpg as Invalid Extension

### ISSUE THREAD

**Issue by justinr86** [cds-snc/report-a-cybercrime#2196]
## Summary

While testing the app in staging @lmcbhvu (Hong) uploaded an image to test Azure Content Moderator. The analyst email was generated and sent successfully but in the **File attachments** section of the report it was indicated that the file was not scanned as it was not a supported type. The uploaded file was a **.jpg** which is in the list of supported file types. 

I tested this locally and the file was scanned successfully so this may have something to do with the environment. For more information on what caused this the staging server logs may need to be reviewed. This report and the file uploaded are attached.

## Steps to reproduce

Create a new report, uploaded attached image, submit report. 

**Expected behavior**:  Report submitted, image attached, content moderator score included.

**Actual behavior**: Report submitted, image attached, report indicates file type is not allowed.

**Report:**
[failedJPGReport.txt](https://github.com/cds-snc/report-a-cybercrime/files/5069899/failedJPGReport.txt)

**Image:**
![fake](https://user-images.githubusercontent.com/62246403/90153761-5e2b2300-dd57-11ea-9189-89ad8ff96e0b.jpg)

**Comment by lmcbhvu** [comment]
This issue cannot be reproduced. It is closed
