### ISSUE TITLE
No feedback email is sent 

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2212]
## Summary

I fill out the midway feedback and final feedback (on thank you page) and no feedback email is sent to my rcmp email 

## Steps to reproduce
1. Fill out some pages on the report and click on "Is there something wrong on this page" button
2. Fill out the feedback and submit
 and
1. Fill out the report until get to thank you page, press "Tell us more" button
2. Fill out the feedback on submit

Expected result: The feedback email should sent to hong.vu@rcmp-grc.gc.ca
Actual result: No email is sent

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by ying-chen-cds** [comment]
This is because the second question ""If you had to report a scam or computer crime in the future, would you use this form again?" in final feedback page is removed. Feedback email template needs to be updated to remove this question too.
