### ISSUE TITLE
Cypress Tests in a windows environment

### ISSUE THREAD

**Issue by ngosset** [cds-snc/report-a-cybercrime#2216]
Cypress tests throwing some errors in a Win10 environment

basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list

**Comment by lmcbhvu** [comment]
Solution: 
1. Edit package.json
2. Go to scripts section (Just remove the node in front of ./node_modules)
3. Replace "cypress:open": "node ./node_modules/.bin/cypress open " to "cypress:open": "./node_modules/.bin/cypress open "

**Comment by ngosset** [comment]
thanks hong.
