### ISSUE TITLE
The fields in How did the suspect reach you? page should be optional.

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2221]
## Summary

In the current prod version, the fields in "How did the suspect reach you?" page is optional. but now it is changed. The user will get an error message "howDidTheyReachYou is a required field" if the user does not choose any field. If we decide the user has to choose at least one field in this page, the error message should be changed to make it more clear

## Steps to reproduce
1. Choose a full report
2. Without choosing any field in "How did the suspect reach you?" page, click on continue

![page1](https://user-images.githubusercontent.com/60269104/90558935-dab06e00-e16a-11ea-9b3d-b1ae17f32dde.jpg)

**Comment by lmcbhvu** [comment]
The error message may be
Select at least one thing that the suspect reached you.
Check at least one box. If you’re not sure, choose “Other”.

**Comment by ngosset** [comment]
Reopening issue. Validation should be removed from this page entirely. It was only added as an example for Formik (see PR #2138 ) but needs to be removed before we go to prod.
