### ISSUE TITLE
Still some English words are found in french report

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2225]
## Summary

Still some English words are found in French report
Please see the below pictures

## Steps to reproduce

1. Submit Full French report

![page1](https://user-images.githubusercontent.com/60269104/90638159-fb280900-e1fa-11ea-9051-022674123b7a.jpg)

![page2](https://user-images.githubusercontent.com/60269104/90638258-1bf05e80-e1fb-11ea-84d1-a02f030fb52e.jpg)

**Comment by dengcn** [comment]
Maybe missed merge in last PR, I will fix these 2
