### ISSUE TITLE
The user cannot skip "When did the incident happen?" 

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2253]
## Summary

With the current prod version, the user can skip "When did the incident happen?" page by click on Continue without selection any option. But now it becomes mandatory. The user has to make a selection. When you make the selection, you have to enter the date, otherwise you will get an error

![file1](https://user-images.githubusercontent.com/60269104/91612519-97fd4b80-e94b-11ea-9710-1746f6f114a5.jpg)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by ying-chen-cds** [comment]
You can choose "I'm not sure" and you don't have to put anything in the text area

**Comment by stephaniemgauthier** [comment]
I agree with the comment above - 'You can choose "I'm not sure" and you don't have to put anything in the text area'

I have change the label above to needs a decision for discussion at the next prioritization meeting.

**Comment by stephaniemgauthier** [comment]
Also noted that the link in the error box points to the landing page - this needs to be fixed pls.

**Comment by ngosset** [comment]
Make it like prod is right now and we will be redesigning the language on this page to be more clear in the future.
