### ISSUE TITLE
Should it go directly to section that the user wants to change instead of back to summary page 

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2276]
## Suggestion / question

At summary page, if the user wants to choose more options in "What could be affected?" page, it should go directly to page that the user wants to add instead of summary page after clicking on <Continue> button

For example The user fills out the report and choose the Other option at "what could be affected?" page. At the summary, the user change their mind and clicks on Edit link at "What could be affected" section. It takes the user to the "What do you think could be affected?" page and the user checks on Money or finances option. When the user clicks on<Continue> button, it should take a user to "How were your money or finances affected?" page instead back to summary page.

With this way, the user will not miss to enter information on "How were your money or finances affected?" page. We should not expect the user needs to know after adding Money and Finances option on what could be effected page, they need to click on edit link at Money and finances section to enter their info.

## Use case

> What would this address?

**Comment by justinr86** [comment]
There is already an open issue about this - #1377.
