### ISSUE TITLE
Feedback Email Error

### ISSUE THREAD

**Issue by justinr86** [cds-snc/report-a-cybercrime#2287]
## Summary

Sending a feedback email (mid-form or final) results in an error. In both cases the error message is "Missing personalisation: feedback".

![feedback_error](https://user-images.githubusercontent.com/62246403/93255226-97e0b680-f767-11ea-9bff-b67fabbe83a4.png)

## Steps to reproduce

1. Create a report.

1. Before submitting the report select the button labeled "Is something wrong with this page?", fill out the feedback form and submit.

1. Check server log.

1. Submit the report.

1. Select the button labeled "Tell us more", fill out the feedback form, and submit.

1. Check server log.

In the server logs you will see the error message for each feedback form submission.

## Unresolved questions

N/A

**Comment by ying-chen-cds** [comment]
Hi Justin, we are using a new email template for our local environment. Please change NOTIFY_FEEDBACK_TEMPLATE_ID in your .env to "NOTIFY_FEEDBACK_TEMPLATE_ID=c1188097-5d01-4ec8-a044-872bfaf29884" and try again

**Comment by justinr86** [comment]
Yes, new template resolves the issue.
