### ISSUE TITLE
Mixed English and French Error in "When did the incident happen" form

### ISSUE THREAD

**Issue by dengcn** [cds-snc/report-a-cybercrime#2312]
## Summary
Mixed English and French Error in "When did the incident happen" form

> One paragraph explanation of the bug.
In the "When did the incident happen" form", if error happens or validation failed, mixed English and French error will be shown on page when the language used is French. See attached picture

## Steps to reproduce
Follow any report work flow, reach When did it happen page, use French, fill nothing or type invalid data which will cause validation error. then the ERROR message will show mixed English and French error.
![WhenDidItHappenFormErrorMixedEnglishAndFrench](https://user-images.githubusercontent.com/5130380/94287940-e25ef180-ff24-11ea-976b-f10229bffb68.jpg)

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by ying-chen-cds** [comment]
The validation should be totally removed. Please refer to #2253 and it is already assigned to Diane.

**Comment by dengcn** [comment]
Since in PR 2253, team had decided to remove validation on this page completely, so we do not need to care English or French in error message.  

https://github.com/cds-snc/report-a-cybercrime/issues/2253
