### ISSUE TITLE
Allow a user to download and print his/her/their report.

### ISSUE THREAD

**Issue by ngosset** [cds-snc/report-a-cybercrime#2314]
See user story & discussion in MS Teams.

We are looking to have a "Print" or "Download" button added to the thank you page. This button should generate a PDF summary of the user's report.

The user can then download this PDF and print it off.

Please use the same layout as the confirmation page for this PDF.

Look at PDF Kit to build the PDF:

https://pdfkit.org/
https://www.npmjs.com/package/pdfkit

**Comment by sdzhangtao** [comment]
If we just print, we can geenrate a printable html, but if you want user to download and save, then pdf is better.

**Comment by ngosset** [comment]
We want download too, let's go the PDF route if it's not too hard.
