### ISSUE TITLE
User left report due to error message received 

### ISSUE THREAD

**Issue by barrhayl** [cds-snc/report-a-cybercrime#2318]
**The Feedback form received Sept 29 @9:30**  

Feedback:
“{"page":"/finalfeedbackthanks","midFeedback":["midFeedback.problem.broken"],"problemDescription":"Getting error message when it comes to report "}”

**Comment by justinr86** [comment]
Need more info to determine cause of issue. Will discuss with @ngosset later today. Currently using the following query, only finding availability checks and new requests:

`AppServiceConsoleLogs | where TimeGenerated > datetime('2020-09-30T09:20:00Z') and TimeGenerated < datetime('2020-09-30T09:40:00Z')
| where parse_json(tostring(parse_json(tostring(parse_json(ResultDescription).meta)).req)).url <> "/ping"`

**Comment by justinr86** [comment]
After examining the logs as a group it appears this issue was likely caused by a client side error. We do not have any indication of an error occurring on Sept. 30th - closing this issue.
