### ISSUE TITLE
No feedback email is received when the user fills out the midway or final feedback when the report is submitted

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2319]
## Summary

No feedback email is received when the user fill out the midway or final feedback when the report is submitted

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by ying-chen-cds** [comment]
In .env, "NOTIFY_FEEDBACK_TEMPLATE_ID" should be "NOTIFY_FEEDBACK_TEMPLATE_ID=c1188097-5d01-4ec8-a044-872bfaf29884". Please ask Dave Heerema to change it in Dev's Azure App settings.

**Comment by lmcbhvu** [comment]
We need to remember to update it in staging and prod as well when the new template is applied

**Comment by ngosset** [comment]
I've changed the template ID in DEV. It is restarting now. We will need to notify cloud ops (Dave) when we go to staging and prod with this change. I think I need to start keeping implementation plans for releases again

**Comment by lmcbhvu** [comment]
I submit a few feedbacks on DEV and I have not received any feedback email

**Comment by lmcbhvu** [comment]
This defect is closed because the NOTIFY_FEEDBACK_TEMPLATE_ID in .env is updated with a new ID. I retested it and it works now
