### ISSUE TITLE
Should we have the same way to display an error message

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2325]
## Summary

There is an inconsistent way to display an error message

For example:
On "Who are you reporting for?" Page, we just display simple message in a pink box 
![image](https://user-images.githubusercontent.com/60269104/94966608-8f101480-04cb-11eb-8a10-50a41949aa19.png)

But on "When did the incident happen?" page, we display more info in the pink box

![image](https://user-images.githubusercontent.com/60269104/94966819-e7471680-04cb-11eb-90e0-eaace3e81e8c.png)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by ngosset** [comment]
The "Who are you reporting for" should be changed to match the "When did the incident happen" form.
