### ISSUE TITLE
Should the error message about wrong date more specific as it did in current prod? 

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2326]
## Summary

The user just gets an error message "Please review the date entered" if the date is entered wrong.
In our current version in prod, it will specific what is wrong with a date .

For example:
If the user enters the future date, the user will get
Please review the date entered
Enter a date from the past.

If the user enters the wrong day or month, the user will get 
Please review the date(s) entered.
Enter a valid day.

Please review the date(s) entered.
Enter a valid month.

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by ngosset** [comment]
Closing for now. Let's revisit if analytics shows a drop off due to new date messges.
