### ISSUE TITLE
Error Summary Link Affects History

### ISSUE THREAD

**Issue by justinr86** [cds-snc/report-a-cybercrime#2340]
## Summary

When an error(s) is present a summary is displayed at the top of the form describing the issue. A link is included in this summary to scroll to the appropriate field. Currently the link uses default behavior so every time it is selected another entry in the browser history is inserted. This affects the Back Button functionality.

## Steps to reproduce

1. Start new report.

1. On Privacy Consent page select Continue without selecting checkbox.

1. When Error Summary is displayed select the link.

1. Select the Back Button, you will remain on the same page.

## Unresolved questions

N/A

**Comment by DianeLiu2019** [comment]
whoareyoureportfor and whatwasaffected page .  so far , in master, if we click the link in the error message ,then click the back button, the page still in the same page , doesn't go back to the previous page, but you fixed the issue in this branch
