### ISSUE TITLE
Should we add extension number to phone number in contact information page

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2344]
## Suggestion / question

An extension to phone number should be added in contact information page.
In analyst email, it should be display (613) 992- 0815 ext.123

![image](https://user-images.githubusercontent.com/60269104/95508370-dc372f00-0980-11eb-9f87-1d5bc56b6684.png)

## Use case

> What would this address?

**Comment by dengcn** [comment]
This is a good idea. If we need to support extension in phone, we need to add such "extension" field

**Comment by stephaniemgauthier** [comment]
duplicate issue
