### ISSUE TITLE
@chakra-ui/core  still be used in HowDidItStartPage.js  

### ISSUE THREAD

**Issue by DianeLiu2019** [cds-snc/report-a-cybercrime#2362]
## Summary

> One paragraph explanation of the bug.
currently, we still use @chakra-ui/core  in HowDidItStartPage.js page, for example:   import { H1 } from './components/header'
import { Stack } from '@chakra-ui/core'   , there maybe more.   we need to replace them by using formik component

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by justinr86** [comment]
At this point we have only updated the forms. The pages still need to be updated.
