### ISSUE TITLE
@chakra-ui/core still be used in FinalFeedbackThanksPage.js 

### ISSUE THREAD

**Issue by DianeLiu2019** [cds-snc/report-a-cybercrime#2363]
## Summary

> One paragraph explanation of the bug.
currently, we still use @chakra-ui/core in FinalFeedbackThanksPage.js ,  for example: import { Layout } from './components/layout'    import { Stack, Box, Icon } from '@chakra-ui/core'  import { Alert } from './components/Messages'
import { Route } from 'react-router-dom'       import { Link } from './components/link'. there maybe more. we need to replace them by using formik component.
## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by justinr86** [comment]
At this point we have only updated the forms. The pages still need to be updated.

**Comment by DianeLiu2019** [comment]
> At this point we have only updated the forms. The pages still need to be updated.

Yes, I probably don't need create an issue for all the pages.
