### ISSUE TITLE
The next label in How were your money or finances affected? page should be changed 

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2365]
## Summary

The next label in How were your money or finances affected? is different with next label in other pages such as "How was your personal information affected?" and "How were your devices or accounts affected?".  Currently, it is "Next: What happened?" and the other pages is "Next: Details about what was affected" 

In prod version, it is "Next: Details about what was affected"  in "How were your money or finances affected?" page

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by ngosset** [comment]
This is a duplicate issue of #1295

**Comment by ying-chen-cds** [comment]
Fixed by PR2417
