### ISSUE TITLE
Extra space after Personal information (in mobile version)

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2379]
## Summary

The extra space is needed after personal information field in "What do you think could be affected?" page when the report is viewed on phone

![image](https://user-images.githubusercontent.com/60269104/96487960-52eaec80-120b-11eb-9316-e565da030907.png)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by DianeLiu2019** [comment]
the issue is fixed in PR #2346
