### ISSUE TITLE
Miss spelling in analyst report

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2380]
## Summary

In analyst report,  report type should be Quick Tip. In French, currently it is soumettre des renseignement.  Should it be "Conseil rapide" for more accurate?

![image](https://user-images.githubusercontent.com/60269104/96495600-1a9cdb80-1216-11eb-835c-4cd452c042cb.png)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by DianeLiu2019** [comment]
The French translation is Cassista gave to me. ![image](https://user-images.githubusercontent.com/51336707/96501016-bd0c8d00-121d-11eb-8329-260b5674538d.png)

**Comment by lmcbhvu** [comment]
I refer renseignements rapides
