### ISSUE TITLE
Accessibility - Empty form label on How were your money or finances affected? page

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2390]
## Summary

Got an error (Emplty form lable) when runs WAVE on How were your money or finances affected? page

![image](https://user-images.githubusercontent.com/60269104/96628542-5ef4ae00-12e0-11eb-83fc-e0aa863ad46c.png)

**Comment by dengcn** [comment]
I checked the master branch on this money lost page with Wave launched and do not see this error, Hong will check again
