### ISSUE TITLE
Should we put something like "Summary of your report" in PDF report

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2395]
## Suggestion / question

It will be nice if we have a title like "Summary of your report" in PDF report. Please see the below picture

![image](https://user-images.githubusercontent.com/60269104/96639794-34125600-12f0-11eb-802b-4815beba5911.png)

## Use case

> What would this address?

**Comment by ngosset** [comment]
Let's keep it this way for now.
