### ISSUE TITLE
It would be nice if all text fields in report are bold and text value are aligned

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2396]
## Suggestion / question

It would be nice if all fields in report are bold or un-bold. Currently, the following fields are not bold
1. You are reporting for
2. Method of contact
3. This could have affected

and their values should be aligned with the other values

![image](https://user-images.githubusercontent.com/60269104/96646098-9f145a80-12f9-11eb-8b2e-3f773a84db31.png)

## Use case

> What would this address?

**Comment by ngosset** [comment]
Needs to be fixed on confirmation page too.
