### ISSUE TITLE
Should the title sections have the same size in PDF report

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2403]
## Suggestion / question

Should the title sections have the same size in PDF report? and should we add more spaces after "What happens next?" and "Stay connected and informed"

![image](https://user-images.githubusercontent.com/60269104/96759928-a80f3580-13a6-11eb-8c74-26e176ad15fa.png)

## Use case

> What would this address?

**Comment by ngosset** [comment]
We won't change this, it's because the headings are for different purposes
