### ISSUE TITLE
The field name is required for text area of "I'm not sure" option in summary and PDF report

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2409]
## Summary

To be consistent, the field name of the text area of "I'm not sure" option on When did the incident happen? page needs to be added in summary and PRD report.
For example: 
For "Who are you reporting for?", if the user choose "A business" and enter info into its text area. In the summary, it will display
**Who are you reporting for?**
**You are reporting for:** A business
**Details**: waltmart in Barrhaven

But it is not applied for "I'm not sure" option on When did the incident happen? page. It displays
**When did the incident happen?**
**Incident frequency**: I'm not sure
I think it happened in mid of September

it should be something like
**When did the incident happen?**
**Incident frequency**: I'm not sure
**Details**: I think it happened in mid of September

![image](https://user-images.githubusercontent.com/60269104/96925850-c9455400-1482-11eb-9327-e1356c6dd5a6.png)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by ying-chen-cds** [comment]
It's the same as confirmation page
