### ISSUE TITLE
Bug - Landing Page

### ISSUE THREAD

**Issue by TarekTraboulsi** [cds-snc/report-a-cybercrime#2411]
Please make changes to submit button [
[Changes to submit button.docx](https://github.com/cds-snc/report-a-cybercrime/files/5425717/Changes.to.submit.button.docx)
](url)

**Comment by justinr86** [comment]
We will need French translation for this update.

**Comment by justinr86** [comment]
New labels with translations:

Start a full report  - Commencer un rapport complet

Submit a general tip  - Soumettre un renseignement

Thanks @TarekTraboulsi
