### ISSUE TITLE
In "mobile view" field border lines disappeared

### ISSUE THREAD

**Issue by danprime** [cds-snc/report-a-cybercrime#415]
Visited (on chrome) https://report-a-cybercrime.cds-snc.ca/scaminfo
View Inspector and set to mobile
ERROR: - See that borders around fields disappeared.

<img width="513" alt="Screen Shot 2019-07-02 at 1 51 38 PM" src="https://user-images.githubusercontent.com/2610409/60534781-95b04a80-9cd0-11e9-9d2c-f5268b24207b.png">
<img width="513" alt="Screen Shot 2019-07-02 at 1 51 22 PM" src="https://user-images.githubusercontent.com/2610409/60534782-95b04a80-9cd0-11e9-96ab-27fd3d793737.png">

**Comment by sastels** [comment]
I noticed this before (on Chrome inspector), but it seems fine on all the real mobile devices I've tried it on 🤷‍♂

**Comment by sastels** [comment]
We'll reopen if this issue occurs on mobile hardware.
