### ISSUE TITLE
Only include information that is filled out on confirmation page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#423]
The confirmation page shows all the fields of the page even if left empty... Should we consider removing them or writing unknown or N/A if missing?

<img width="647" alt="Screen Shot 2019-07-02 at 6 24 59 PM" src="https://user-images.githubusercontent.com/38330843/60550678-c60adf80-9cf6-11e9-9047-c917118dd167.png">

<img width="673" alt="Screen Shot 2019-07-03 at 10 02 29 AM" src="https://user-images.githubusercontent.com/38330843/60597953-d7490000-9d79-11e9-86a2-321b21ba6194.png">

**Comment by sastels** [comment]
resolved by #446
