### ISSUE TITLE
Date picker expands under the keyboard (in iPad)

### ISSUE THREAD

**Issue by danprime** [cds-snc/report-a-cybercrime#428]

**Comment by sastels** [comment]
Solution might be to move the date field to the top of the screen when it gets focused on.

**Comment by anikbrazeau** [comment]
In testing we saw the date picker allow users to type words, but then not accept what was typed if it was in a different format. The blank date prevented people from progressing to the following page.

**Comment by anikbrazeau** [comment]
Perhaps P2 could allow for a more flexible input giving the option to type, guided by prompts that we're looking for the general timeframe in the form of dates (when it started, when it last occurred).

**Comment by sastels** [comment]
It's been gone for a while! 🎉
