### ISSUE TITLE
Make "New report" link on Thank You page a green button

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#433]
Making the "Report another scam" call-to-action a button like on the landing page so that reporting again stands out as the clear action to take.

<img width="744" alt="Screen Shot 2019-07-03 at 3 46 55 PM" src="https://user-images.githubusercontent.com/38330843/60620688-e3e54c80-9da9-11e9-907e-2368a43df677.png">

So that it looks more like this: 

<img width="213" alt="Screen Shot 2019-07-03 at 3 46 34 PM" src="https://user-images.githubusercontent.com/38330843/60620696-e778d380-9da9-11e9-958b-d9a4a4b198b2.png">

"Report another scam"

**Comment by sastels** [comment]
done by #434
