### ISSUE TITLE
P2 landing page

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#525]
<img width="235" alt="image" src="https://user-images.githubusercontent.com/8228248/62722716-130c6080-b9dd-11e9-97b4-bc96d81131b3.png">

**Comment by danprime** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Build Pages for Prototype 2](https://trello.com/c/pGspCQOM/433-build-pages-for-prototype-2)
