### ISSUE TITLE
P2 Timeframe page

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#526]
<img width="140" alt="image" src="https://user-images.githubusercontent.com/8228248/62722847-4d75fd80-b9dd-11e9-94b2-7b63882fc0aa.png">

**Comment by danprime** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Build Pages for Prototype 2](https://trello.com/c/pGspCQOM/433-build-pages-for-prototype-2)

**Comment by DianeLiu2019** [comment]
finished the task. associated with time frame page #558
