### ISSUE TITLE
P2 What happened page

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#527]
<img width="204" alt="image" src="https://user-images.githubusercontent.com/8228248/62722899-69799f00-b9dd-11e9-9c68-dad7b20ad74a.png">

**Comment by danprime** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Build Pages for Prototype 2](https://trello.com/c/pGspCQOM/433-build-pages-for-prototype-2)
