### ISSUE TITLE
P2 scammer details page

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#528]
<img width="152" alt="image" src="https://user-images.githubusercontent.com/8228248/62722933-82825000-b9dd-11e9-87a4-98a9ab3accc2.png">

**Comment by danprime** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Build Pages for Prototype 2](https://trello.com/c/pGspCQOM/433-build-pages-for-prototype-2)
