### ISSUE TITLE
P2 impact statement page

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#529]
<img width="96" alt="image" src="https://user-images.githubusercontent.com/8228248/62722975-9928a700-b9dd-11e9-8fba-a1c3d2e71c01.png">

**Comment by danprime** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Build Pages for Prototype 2](https://trello.com/c/pGspCQOM/433-build-pages-for-prototype-2)

**Comment by danprime** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Build Pages for Prototype 2](https://trello.com/c/pGspCQOM/433-build-pages-for-prototype-2)

**Comment by danprime** [comment]
This was completed with Pull Request #560
