### ISSUE TITLE
P2 contact info page

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#530]
<img width="109" alt="image" src="https://user-images.githubusercontent.com/8228248/62723020-b493b200-b9dd-11e9-99cf-fe5be2447060.png">

**Comment by danprime** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Build Pages for Prototype 2](https://trello.com/c/pGspCQOM/433-build-pages-for-prototype-2)
