### ISSUE TITLE
P2 next steps page

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#532]
<img width="139" alt="image" src="https://user-images.githubusercontent.com/8228248/62723129-f15fa900-b9dd-11e9-8726-d777bdda918f.png">

**Comment by danprime** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Build Pages for Prototype 2](https://trello.com/c/pGspCQOM/433-build-pages-for-prototype-2)

**Comment by danprime** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Build Pages for Prototype 2](https://trello.com/c/pGspCQOM/433-build-pages-for-prototype-2)
