### ISSUE TITLE
Lost information going back from Thank-you page

### ISSUE THREAD

**Issue by danprime** [cds-snc/report-a-cybercrime#578]
A bit weird behaviour, after going through the form and filling it out to the thank you page. If you go back from the Thank-you you get a blank confirmation page. 

This was uncovered during usability testing when participants wanted to go back from the Thank-you page just to verify something.

**Comment by sastels** [comment]
Hrm, we’re scrubbing the data when the user gets to the thank you page in P1 (though not in P2)
https://github.com/cds-snc/report-a-cybercrime/blob/master/frontend/src/p1/ThankYou.js#L20

Deleting those lines will fix this.
