### ISSUE TITLE
P1 - Create unique visual styles for buttons that perform different functions.

### ISSUE THREAD

**Issue by melbanyard** [cds-snc/report-a-cybercrime#596]
**Problem:** On the final page, participants were unsure if they had successfully submitted a report. Some participants were unsure what would happen if they closed the page, or assumed they had to file another report because the green button at the bottom of the page was labelled “submit another report. 

**Evidence:**
- P1) Clicked "Signalez une autre fraude" thinking it was the next button. Became frustrated she had to do it all over again. "Do I have to do more?"
- P1) Reads "vous pourriez aussi..." and says "isn't what I did enough?"
- P6) Does not want to signal another fraud. Would like to go back to main menu.
And, 
- P3) "It is not clear how to get out of here. Can I go back? What would happen to my report."

**Recommendation:** Create unique visual styles for buttons that perform different functions. Style the “next buttons” differently from the “submit” button. In order to avoid framing “submit another report” as a required next step, style it with less emphasis than the “submit button.” 

**Recommendation:** Offer stronger confirmation (ie. with more visual emphasis) that a report has been successfully submitted

**Comment by anikbrazeau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Making changes to content for P1](https://trello.com/c/wy8tKYrW/448-making-changes-to-content-for-p1)

**Comment by nmakuch** [comment]
## This issue is being taken care of in [Pull Request 615](https://github.com/cds-snc/report-a-cybercrime/pull/615)

**Comment by nmakuch** [comment]
Closing as we have merged in 615
