### ISSUE TITLE
P1 - Label each stage in the breadcrumb. Preview this breadcrumb up-front.

### ISSUE THREAD

**Issue by melbanyard** [cds-snc/report-a-cybercrime#597]
**Problem:** Participants were not able to predict what they would be asked to do next, from page to page and at the onset of using the prototype. 

**Evidence:**
P6) Wonders when contact information will be asked for
P2) “Aucune idee” what will happen next
P3) says: I know the first page told me what to do, but I forgot. I see what I could do, but I didn't have the chance to memorize the process on the 1st page.

**Recommendation:** Label each stage in the breadcrumb. Preview this breadcrumb up-front.

**Comment by melbanyard** [comment]
@nmakuch keeping in mind the discussion we had in slack, I'm open to alternative solutions as long as they fix the issue of people not being able to prepare or predict what willl happen next (this was surfaced as a need early on in research)

**Comment by anikbrazeau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Making changes from usability testing to P1](https://trello.com/c/wy8tKYrW/448-making-changes-from-usability-testing-to-p1)

**Comment by nmakuch** [comment]
^ haha crap I never saw that @anikbrazeau my bad

**Comment by nmakuch** [comment]
Closing this as it was addressed in [Pull Request 668](https://github.com/cds-snc/report-a-cybercrime/pull/668)
