### ISSUE TITLE
App crashes on blank dates

### ISSUE THREAD

**Issue by danprime** [cds-snc/report-a-cybercrime#598]
On P1 go to /scaminfo
Erase the default date (and leave it blank)
Click Continue
*CRASH* 

TypeError: Cannot read property 'toISOString' of null

See screenshot
<img width="532" alt="Screen Shot 2019-08-21 at 3 45 47 PM" src="https://user-images.githubusercontent.com/2610409/63463249-ce47e700-c42a-11e9-8129-9181e4e84039.png">

**Comment by anikbrazeau** [comment]
Thoughts on starting the dates blank by default?

**Comment by danprime** [comment]
Wrote a fix to prevent the app from crashing. We can talk about how to handle blank date from a UX perspective later on.
