### ISSUE TITLE
Move expectations to under Tell Us More in the Confirmation Page

### ISSUE THREAD

**Issue by danprime** [cds-snc/report-a-cybercrime#603]
Moving the prompts under the Tell Us More page will help remove the confusion from error and hopefully get the victims to understand the impact of providing more information.

<img width="532" alt="Screen Shot 2019-08-22 at 10 25 04 AM" src="https://user-images.githubusercontent.com/2610409/63523019-60053200-c4c7-11e9-9e4e-aa38b47ddbed.png">

**Comment by sastels** [comment]
app redesigned.
