### ISSUE TITLE
Differentiate the file upload button from the Continue button

### ISSUE THREAD

**Issue by danprime** [cds-snc/report-a-cybercrime#604]
<img width="529" alt="Screen Shot 2019-08-22 at 10 28 40 AM" src="https://user-images.githubusercontent.com/2610409/63523183-a65a9100-c4c7-11e9-93df-ea88704dadc9.png">

**Comment by nmakuch** [comment]
## This issue is being taken care of in [Pull Request 615](https://github.com/cds-snc/report-a-cybercrime/pull/615)

**Comment by nmakuch** [comment]
Closing as we have merged in 615
