### ISSUE TITLE
Add link for Report Again in Thank You Page P2

### ISSUE THREAD

**Issue by danprime** [cds-snc/report-a-cybercrime#605]
Make the reporting again (both english and french) linkable

<img width="529" alt="Screen Shot 2019-08-22 at 10 30 44 AM" src="https://user-images.githubusercontent.com/2610409/63523338-f89bb200-c4c7-11e9-8055-3e627b07328c.png">

**Comment by nmakuch** [comment]
## This Issue is being taken care of in [Pull Request 615](https://github.com/cds-snc/report-a-cybercrime/pull/615)

**Comment by nmakuch** [comment]
Closing as we have merged in 615
