### ISSUE TITLE
Add a date option for cases that took place over a period of time (the ability to choose two separate dates, a start and a finish).

### ISSUE THREAD

**Issue by melbanyard** [cds-snc/report-a-cybercrime#607]
**Problem:** The date picker on “Decrivez la fraude” was difficult for several participants to navigate use. It was difficult to use in two ways: 
1 - It was not clear to some participants that you can type the date in, rather than picking it.
2 - Some participants found it difficult to recall the date if it was from a long time ago, OR took place over a period of time. 

**Evidence for 1:** 
P3) Case was from 2004, starts pressing the date to go back, and then realizes she can type it in
Evidence for 2: 
P2) Unsure how he will be able to continue properly since he hasn't put the right date in.
P5) It asks me for a date, but what if it was over a period of time
P2) Puts the last dates that they can remember, but isn't sure they're accurate

**Recommendation:** Add a date option for cases that took place over a period of time (the ability to choose two separate dates, a start and a finish).

**Comment by anikbrazeau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Making changes to content for P1](https://trello.com/c/wy8tKYrW/448-making-changes-to-content-for-p1)

**Comment by sastels** [comment]
We essentially cha bed the way we do dates along these lines in P2
