### ISSUE TITLE
Offer an option for reporters to describe and name documents they attach

### ISSUE THREAD

**Issue by melbanyard** [cds-snc/report-a-cybercrime#610]
**Problem:** On the “attach additional documents” page (ie. evidence page) participants were unsure how to share non-computer related evidence.
And, Participants were also unsure how they could attach multiple documents at a time.

**Evidence:**
P2) Does not know how to share any details that have to do with a scam phone call
And,
P3) Is not sure if she can attach multiple documents
P5) asks if it could upload more than one file at a time.

**Recommendation:** Offer an option for reporters to describe what the document is.

**Recommendation:** List an example of what kind of document can be uploaded that includes phone related issues (if possible).

**Recommendation:** Similar to the previous recommendation regarding button styling, do not use the same styling for the “attach files” button as is used for the next button.

**Comment by anikbrazeau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Making changes from usability testing to P1](https://trello.com/c/wy8tKYrW/448-making-changes-from-usability-testing-to-p1)

**Comment by anikbrazeau** [comment]
<img width="582" alt="Screen Shot 2019-09-03 at 4 00 25 PM" src="https://user-images.githubusercontent.com/38330843/64204537-fb9d8780-ce63-11e9-947a-0ee0c9a11af7.png">

**Comment by anikbrazeau** [comment]
@nmakuch, thoughts on the attach file button being a different colour from the next button?

**Comment by anikbrazeau** [comment]
Resolved: 

<img width="208" alt="Screen Shot 2020-01-15 at 11 34 50 PM" src="https://user-images.githubusercontent.com/38330843/72493715-b9ac2700-37ef-11ea-982f-bdf40103a319.png">
