### ISSUE TITLE
RCMP logos are slightly different in English vs French

### ISSUE THREAD

**Issue by pcraig3** [cds-snc/report-a-cybercrime#638]
It's pretty subtle but there are very slight differences in the French/English RCMP crests. 

- English logo has an extra white ring surrounding the bull
- English logo has more fur
- English logo is a pixel or two higher

| en | fr |
|----|----|
| extra white ring surrounding the oval with the buffalo. Also the buffalo has more fur.   |  No extra white ring surrounding the buffalo.  Less fur above left eye. |
|  ![image](https://user-images.githubusercontent.com/2454380/63806615-fb444000-c8e9-11e9-91b8-f60797fbced0.png)  |  ![image](https://user-images.githubusercontent.com/2454380/63806588-eb2c6080-c8e9-11e9-8056-9a0cff7182a3.png)  |

It's a bit easier to see as a GIF.

## gif 

![rcmp](https://user-images.githubusercontent.com/2454380/63806880-8de4df00-c8ea-11e9-9c16-943a7b1bdf20.gif)

**Comment by pcraig3** [comment]
After investigating by looking at @melbanyard's pop socket, it seems like the missing white ring is yellow on the colourized version. ([wikipedia confirms](https://en.wikipedia.org/wiki/Royal_Canadian_Mounted_Police#/media/File:Royal_Canadian_Mounted_Police.svg).) So I would guess the logo with the extra white ring is the correct version, and the French version is not accurate.

Probably this should be a high priority item up at the next sprint review.

**Comment by pcraig3** [comment]
![64706837-2305dd00-d480-11e9-8735-c819c41a1cd8](https://user-images.githubusercontent.com/2454380/64707833-9e1bc300-d481-11e9-9e1c-7754b830180e.png)


---

![pika](https://user-images.githubusercontent.com/2454380/64707268-c3f49800-d480-11e9-85bf-fffd31d2f066.png)

**Comment by anikbrazeau** [comment]
This no longer applies to this site as we are using GoC branding instead.

<img width="869" alt="Screen Shot 2020-02-11 at 4 42 18 PM" src="https://user-images.githubusercontent.com/38330843/74282072-845f0000-4ced-11ea-928f-b06f1ea5ac3d.png">
