### ISSUE TITLE
Participants were unsure how to fill out the “Tell us more about the impact” textbox on step 4 if they had not lost anything. 

### ISSUE THREAD

**Issue by melbanyard** [cds-snc/report-a-cybercrime#640]
**Issue:** Participants were unsure how to fill out the “Tell us more about the impact” textbox on step 4 if they had not lost anything. Some filled out the textbox with potential losses.

Some would write in the textbox before checking off the checklist. 

**Evidence:**
P5) For impact writes that she no longer has "confiance dans l'internet" and that she will no longer use her computer.
P3) Added the potential impact. said that if the scammer had gained access he would have lost 100's of dollars of in-game items

**Recommendation:** Consider placing less visual emphasis on the textbox, and more on the checklist. Find a way to better relate the content of the textbox, to that of the checklist through visual cues.

**Comment by anikbrazeau** [comment]
PR: #673 
<img width="448" alt="Screen Shot 2019-08-30 at 4 37 30 PM" src="https://user-images.githubusercontent.com/38330843/64049923-83be1d00-cb44-11e9-9d0b-b1268cbbfd5c.png">
