### ISSUE TITLE
(Same issues as P1) Participants were not able to predict what they would be asked to do next, from page to page and at the onset of using the prototype. 

### ISSUE THREAD

**Issue by melbanyard** [cds-snc/report-a-cybercrime#643]
**Issue:** Repeated from P1: Participants were not able to predict what they would be asked to do next, from page to page and at the onset of using the prototype. https://github.com/cds-snc/report-a-cybercrime/issues/597

**Evidence:** 
Several continued to anticipate entering contact info on the next page
P2 - Tells us that someone will offer help for her situation on the following page.
PAGE 5. P2 - Not sure what will happen next.

**Recommendation:** Label each stage in the breadcrumb. Preview this breadcrumb up-front. Use the buttons at the bottom and the top to indicate what will be on the following pages, (esp. On mobile).

**Comment by nmakuch** [comment]
Closing this because it was addressed in [Pull Request #668](https://github.com/cds-snc/report-a-cybercrime/pull/668)
