### ISSUE TITLE
(Similar to P1)  On step 1 “when did it happen” participants found the date picker interaction difficult to use. (Sub-issues on this page detail problems). 

### ISSUE THREAD

**Issue by melbanyard** [cds-snc/report-a-cybercrime#644]
**Sub-issue:** Some skipped past the date picker because it was auto-filled with content.
P3) Skipped straight to continue because the fields were already filled. 

**Sub-issue:** It was not clear to some participants that you can type the date in, rather than clicking back to it via the calendar picker. 
P5) was about to type the date but then the calendar came up and she started to go through all the dates to get a few years back.
P2) Starts clicking back through the calendar to get to 2016. Takes awhile.

**Sub-issue:** The numerical date format was difficult for some people to read. 
P4) "La date est en anglais" --- re: format

**Comment by sastels** [comment]
What if we scrapped the datepicker and just had three inputs: day, month (maybe a dropdown) and year?

**Comment by nmakuch** [comment]
I think that's less confusing for sure.  👍🏽

We could have another set of identical inputs (optional) for people who need to specify a range maybe?

**Comment by anikbrazeau** [comment]
Do we even need to get as granular as day?

Could we do [Month] / [Year] ?

**Comment by sastels** [comment]
superseded by #712
