### ISSUE TITLE
Some participants put multiple incidents into the “Qu’est-ce qui s’est passe” test box. 

### ISSUE THREAD

**Issue by melbanyard** [cds-snc/report-a-cybercrime#647]
**Issue:** Some participants put multiple incidents into the “Qu’est-ce qui s’est passe” test box. They then listed out multiple impacts / amounts loss in step 4. 

**Evidence:** 
P5) Adds 2 complaints into the textbox (2 events), separates them by pressing enter.
P1) talking about a combination of scams and impacts of all of them on step 4

**Recommendation:** We need to have a larger discussion about this :) For now my recommendation is to leave it actually, and see what we get from the large test. But in the long run, we should know if this kind of information is useful for the NC3.

**Comment by sastels** [comment]
app redesigned
