### ISSUE TITLE
(Same as P1) participants were unsure how they could provide details if they did not know who the scammer was for certain.

### ISSUE THREAD

**Issue by melbanyard** [cds-snc/report-a-cybercrime#648]
**Issue:** https://github.com/cds-snc/report-a-cybercrime/issues/608 "Participants expressed confusion on the “add scammer details” choices page. On the page where participants choose to proceed or not, some participants were unsure how they could provide details if they did not know who the scammer was for certain.”

**Evidence:** 
P4) je sais "absolument rien"
P6) hardest part = "décrire la personne... sait pas c'est qui"
P3) Says it is hard to know what to add since he doesn't know this person.

**Recommendation:** Provide specific examples of what scammer details may be (on both pages). Ensure it is clear to reporters that we are not asking for the actual address or phone number of the scammer, but whatever address or phone number was used to contact them.

Consider “tell us about the scammer” instead of “share any identifying details about the scammer.”

**Comment by anikbrazeau** [comment]
<img width="463" alt="Screen Shot 2019-08-29 at 1 59 39 PM" src="https://user-images.githubusercontent.com/38330843/63964510-459dfc00-ca65-11e9-8af6-b198266ba2ef.png">
