### ISSUE TITLE
Under “add scammer details" , participants added details without context.

### ISSUE THREAD

**Issue by melbanyard** [cds-snc/report-a-cybercrime#649]
**Issue:** Entering specific details, under “add scammer details" but without context.

**Evidence:** 
P5 - Put in names that the scammer had used (LLC, Tech.4u + more) but without context.
P5 - Instead of specifying address she writes "4 addresse aux USA... 2 addresses differentes"

**Recommendation:** Consider providing an example.

**Comment by anikbrazeau** [comment]
Provide hits/guidance
+ Added examples

For examples:
<img width="540" alt="Screen Shot 2019-09-03 at 10 53 39 PM" src="https://user-images.githubusercontent.com/38330843/64222326-b26a2980-ce9d-11e9-8a4f-7b7bd7749e28.png">
