### ISSUE TITLE
 On step 6, “review your report” people did not know what detail to put in the “tell us more” textbox. 

### ISSUE THREAD

**Issue by melbanyard** [cds-snc/report-a-cybercrime#650]
**Issue:** On step 6, “review your report” people did not know what detail to put in the “tell us more” textbox. It became distracting as a result. 

“The more detail you can give, the more police will have to go on.” is ambiguous. 

**Evidence:** 
P1 - commented he'd have nothing more to add
P3 - "Donnez plus de details... c'est un peu vague"
P5 - Isn't sure what else she could add.

**Recommendation:** Remove the tell us more textbox and let people add details to their report on this screen. Or, provide an example of what details might also be useful that may have been missed. 

As a rule, the best directions should be placed in the main titles, rather than the small text below.

**Comment by anikbrazeau** [comment]
Remove tell us more box.
Linked to issue #603 https://github.com/cds-snc/report-a-cybercrime/issues/603
