### ISSUE TITLE
Date Selection not being respected

### ISSUE THREAD

**Issue by danprime** [cds-snc/report-a-cybercrime#665]
Launch P2
Select a date that is not today.
Go to Confirmation 
*ERROR* See that the date selected is today's date (default) as opposed to the selected date.

<img width="596" alt="Screen Shot 2019-08-29 at 9 53 54 AM" src="https://user-images.githubusercontent.com/2610409/63946474-35752500-ca43-11e9-9854-92bd6a3071b6.png">
<img width="596" alt="Screen Shot 2019-08-29 at 9 53 45 AM" src="https://user-images.githubusercontent.com/2610409/63946477-373ee880-ca43-11e9-8002-2766eb02456c.png">

**Comment by DianeLiu2019** [comment]
the task completed. associated with pull request #682
