### ISSUE TITLE
Google Analytics doesn't load in Chrome

### ISSUE THREAD

**Issue by lchski** [cds-snc/report-a-cybercrime#676]
Noticed on @DianeLiu2019's computer. `analytics.js` call errors out in Network tab, with errors in Console tab. Works in Firefox.

<img width="1440" alt="Screen Shot 2019-08-30 at 2 14 37 PM" src="https://user-images.githubusercontent.com/343884/64044724-86654600-cb35-11e9-98f7-4014615998a3.png">

```
The FetchEvent for "https://www.google-analytics.com/analytics.js" resulted in a network error response: an object that was not a Response was passed to respondWith().
Promise.then (async)
(anonymous) @ service-worker.js:43

loadGA.js:21 GET https://www.google-analytics.com/analytics.js net::ERR_FAILED
Ho @ loadGA.js:21
ca @ core.js:112
ftlp @ TrackPageViews.js:8
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83

The script has an unsupported MIME type ('text/html').

scaminfo:1 Uncaught (in promise) DOMException
```

**Comment by danprime** [comment]
Can't seem to replicate this on the most recent versions (p1, p2, CAFC) https://www.report-a-cybercrime.alpha.rcmp-grc.gc.ca/p1 . Can you check again?

**Comment by lchski** [comment]
Turns out you shouldn’t have UBlock enabled if you want Google Analytics to work! Couldn't replicate this error on my install of Chrome.

Do get this error from the service worker (cc @sastels), though: `Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0`

**Comment by sastels** [comment]
huh, no idea, we should look into that. The PWA still works from my phone though 🤷‍♂

**Comment by danprime** [comment]
Can't replicate. Recommend we close this issue and create a new one for the service worker.
