### ISSUE TITLE
change date picker to text input

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#712]
scrap the date picker!!!!

change to a single text input.

At least in P2

**Comment by anikbrazeau** [comment]
Should we use something like this ? 
https://design-system.service.gov.uk/components/date-input/

**Comment by sastels** [comment]
Initially (ie in the next half hour?) I was going to just make one big field, but we can definitely refine it more later

**Comment by taowa** [comment]
Is mm-dd-yyyy temporary? TBS [[EN](https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-style-guide.html#wp4-7)/[FR](https://www.canada.ca/fr/secretariat-conseil-tresor/services/communications-gouvernementales/guide-redaction-contenu-canada.html#wp4-6)] style for canada.ca sites is yyyy-mm-dd.

**Comment by sastels** [comment]
> Is mm-dd-yyyy temporary? TBS [[EN](https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-style-guide.html#wp4-7)/[FR](https://www.canada.ca/fr/secretariat-conseil-tresor/services/communications-gouvernementales/guide-redaction-contenu-canada.html#wp4-6)] style for canada.ca sites is yyyy-mm-dd.

I think we are planning to go with whatever is least confusing for the users (still TBD), and reformat in the backend if required 👍

**Comment by anikbrazeau** [comment]
sounds perfect!!
