### ISSUE TITLE
Integrate Azure Application Insights

### ISSUE THREAD

**Issue by keithiancolbourne** [cds-snc/report-a-cybercrime#777]
Integrating Azure App Insights will give us greater observability into how our application is performing, communication between services, metrics, user flows, more...
https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview

**Comment by sastels** [comment]
Probably not much chance of getting work out of @keithiancolbourne on this issue 😛 I'll remove him but keep the issue, we need to figure this out at some point before launch...

**Comment by davidheerema** [comment]
App Insights is a hooked-in ms comparator to google analytics, which we're currently using.  As far as I understand :)
