### ISSUE TITLE
“Full name” input not allowing prefilled in content

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#816]

**Comment by sastels** [comment]
Works in Chrome
![image](https://user-images.githubusercontent.com/8228248/67403542-1779fb80-f580-11e9-9923-c814c3740d2f.png)

In Firefox, only the email can use prefilled in content

In Safari only the Full name can use prefillied in content

😞

**Comment by khalidelaggan** [comment]
Will work on this today

**Comment by ngosset** [comment]
@khalidelaggan Hey Khalid - Reviewing all the old/stale issues. Can we close this one or is it still work in progress?

**Comment by khalidelaggan** [comment]
Confirmed this is was in our old prototype
