### ISSUE TITLE
Address IE button link bug

### ISSUE THREAD

**Issue by keithiancolbourne** [cds-snc/report-a-cybercrime#938]
The navigation buttons are not working in IE. This happened again today in usability testing, the user had to switch to Firefox to continue with testing. He was using IE11.

**Comment by sastels** [comment]
Keyboard navigation on Firefox and Safari are also a bit dicey. We should figure out if we're going to switch to Chakra / Grommet ASAP - this will fix some issues (and undoubtedly create more)
