### ISSUE TITLE
Visual elements in buttons (like “report now”) are described in ALT test  

### ISSUE THREAD

**Issue by melbanyard** [cds-snc/report-a-cybercrime#947]
_“The button is labelled but other than hearing report now i am also hearing the kind of arrow that is being used in the graphic”
“Upload icon, add file button” instead of “upload file”_

Occurs across multiple browsers and pages

Recommendation: Keep labels on buttons to the action they’re describing.

**Comment by amazingphilippe** [comment]
This has been fixed with the implementation of Chakra
