### ISSUE TITLE
On Date & contact info page, text format example isn’t visible to blind participants. 

### ISSUE THREAD

**Issue by melbanyard** [cds-snc/report-a-cybercrime#951]
_“the example isn't clear enough. I don't know how it would be punctuated. the format it is accepting [for date] is unclear"_

_Fills out the date as “november 18, 2019” instead of following date convention above._

_This happened on the contact info page as well: 
“Some sites don’t like if you put a space in the postal code, is that the case?”_

**Comment by DianeLiu2019** [comment]
the task was completed. associate with PR #974
