### ISSUE TITLE
Some text fields are described twice for blind participants using screenreaders. 

### ISSUE THREAD

**Issue by melbanyard** [cds-snc/report-a-cybercrime#952]
Occurred on: “What happened”, “Suspect clues” “Impact” 

Blind participants hear the title and example for the textbox, and then hear it again when they tab into the textbox to begin typing. 

_"would be easier if text field were on a line by itself, after this explanatory text"_

**Comment by amazingphilippe** [comment]
More context: Using voiceover on safari on macOs, using keyboard arrows to navigate the page, the labels will be read as text, then as a field group when focusing on the text input

**Comment by khalidelaggan** [comment]
@melbanyard @amazingphilippe this should no longer be an issue as we have refactored the form labels along with the checkboxes.

**Comment by khalidelaggan** [comment]
During my manual test yesterday, I haven't noticed any of these errors occurred
