### ISSUE TITLE
Upload File button on “suspect clues” page is made of separate groups when using screen reader

### ISSUE THREAD

**Issue by melbanyard** [cds-snc/report-a-cybercrime#953]
_“upload icon add file upload button...its repetitive”
“There’s an upload file icon group which i can’t interact with.”_

_“There’s a random part here that says upload icon group” “Theres a few things that are allowing me to upload photo” the button is deconstructed, “three things that are letting me do the same command”_

**Comment by amazingphilippe** [comment]
Fixed with Chakra ui.

More context: When reading text on a page with voiceover on safari on macOs, both the button and its text can be read using arrow navigation.
