### ISSUE TITLE
On review page: All inputs read as 1 line, with no spaces or pauses on screen readers

### ISSUE THREAD

**Issue by melbanyard** [cds-snc/report-a-cybercrime#954]
_Goes back to edit their name because to them it sounds like it all sounds like one word._

_“Its confusing b/c the checkbox is right next to what i wrote"_

_While reviewing impact: Hard to read b/c it reads both the boxes that were checked, and the free text as one line, no periods. "reads the whole line as if it is one sentence" relying on memory to know what he wrote_

**Comment by amazingphilippe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Apply findings from Nov Usability Testing w/ Blind and low vision participants (to existing prototype)](https://trello.com/c/EDa35Fdi/51-apply-findings-from-nov-usability-testing-w-blind-and-low-vision-participants-to-existing-prototype)

**Comment by ngosset** [comment]
Going to close this one within the next couple days unless objects?  It's from November and the former prototype 2, not the current version. The component library, markup, etc.. have all changed a lot. 

@amazingphilippe @khalidelaggan  Thoughts? Maybe we can use a screen reader on one of those accessibility lunch in learns to see if we have any similar issues with the current version.

**Comment by khalidelaggan** [comment]
This is tested with Windows machine and I can't re-produce it in our current app version

**Comment by khalidelaggan** [comment]
I will test on mac shortly to confirm

**Comment by khalidelaggan** [comment]
Adding @lmcbhvu

**Comment by khalidelaggan** [comment]
Tested and passed
