### ISSUE TITLE
header and footer merged in IE

### ISSUE THREAD

**Issue by sastels** [cds-snc/report-a-cybercrime#987]
* works fine on Edge
* in the DOM in the correct order (so that keyboard nav goes through the main content before getting to the header)
* I think it's because we're using css flex, which has dodgy support in IE. See https://developer.mozilla.org/en-US/docs/Web/CSS/flex

![image](https://user-images.githubusercontent.com/8228248/70543685-c7a7c180-1b38-11ea-894f-253673e577d8.png)

**Comment by amazingphilippe** [comment]
Fixed with PR #1039
